### ISSUE TITLE
acts_as_tree alias will still be defined if a colliding gem name occurs lexically after ancestry

### ISSUE THREAD

**Issue by matthewkcarr** [stefankroes/ancestry#103]
For instance if I install the closure_tree gem the ancestry gem will still define acts_as_tree even though it is defined in closure_tree as well.  This breaks the closure_tree gem definition of acts_as_tree.  My guess is that ancestry is loaded before closure_tree and that is why the code breaks.

**Comment by gchan** [comment]
Unsure if this is still a problem for you but I just encountered this problem myself. 
We were on version 1.2.0 of `acts_as_tree` and 1.3.0 of `ancestry` (pretty old project).

We found a combination which worked for us:

```ruby
gem 'acts_as_tree', '~> 1.6.1'
gem 'ancestry', '~> 2.0.0'
```

Hope this helps you or anyone else in this predicament.

**Comment by marnen** [comment]
Similarly here. Ancestry 2.0.0 works with acts_as_tree, but 2.1.0 doesn't.

**Comment by MGPalmer** [comment]
Ditto here.

**Comment by kbrock** [comment]
This is by design and mentioned in the readme.

Is there a request to not define `acts_as_tree`?
Is it still a problem with `2.1.0` and newer?

**Comment by crazymykl** [comment]
This only _became_ a problem in 2.1.0 and newer.

**Comment by crazymykl** [comment]
Here is a workaround:
```ruby
ActsAsTree::ClassMethods.instance_method(:acts_as_tree).bind(self).call
```

Write that where you would've written `acts_as_tree`. (It works with arguments, too.)
