### ISSUE TITLE
Select nodes without childrens

### ISSUE THREAD

**Issue by link82** [stefankroes/ancestry#120]
Hello, I'm trying to figure out how to tell Ancestry to retrieve all the nodes that does not have any children (last level in my tree, all the leaves)

Thanks in advance,
Davide

;)

**Comment by antstorm** [comment]
Here's a PR that adds support for `leaves` scope — #238

**Comment by kbrock** [comment]
see also #50

**Comment by kbrock** [comment]
this is a dup of 50
