### ISSUE TITLE
Avoid N + 1 queries

### ISSUE THREAD

**Issue by lucasas** [stefankroes/ancestry#140]
Hi guys,

First of all, thank you for the great work with this gem.

I have some performance issues here, because N + 1 queries using ancestry.

I have a model:

```
class Category < ActiveRecord::Base
   acts_as_tree
end
```

And I want to load all root categories loading all children of each one.

```
roots = Category.roots
roots.each { |r| r.children }
```

I want to execute only 2 queries here. I was looking for this into source code, but I didnt find it. Is there any plan to solve this performance issue?

Thank you.

**Comment by alexanderadam** [comment]
Sorry for reviving this issue but is there nowadays some integration for `includes` / `eager_load` / `preload` in ancestry?

**Comment by kbrock** [comment]
@alexanderadam I'm sorry to say that no. at this time there is no `includes` support

**Comment by alexanderadam** [comment]
What a pity. Thank you for responding so fast.
Could #440 stay open or is it possible to reopen this issue here so that everybody can see that this isn't solved yet?
