### ISSUE TITLE
i can't find arrange_serializable method

### ISSUE THREAD

**Issue by i5ting** [stefankroes/ancestry#173]
hi 

```
undefined method `arrange_serializable' for #<Class:0x007fc26ce0ac78>
```

am i use the previos version?

**Comment by nhodges** [comment]
@stefankroes any way you can publish a new version?

**Comment by kbrock** [comment]
@nhodges thanks for the ping. Will get it out there

**Comment by aximuseng** [comment]
I have 3.0.7 installed and I am still getting this error - no other issues with the gem to report.

**Comment by kbrock** [comment]
@aximuseng thanks for pinging 

Do you also get the problem with pointing to master? (read: is the fix as simple as pushing a new version?)

Can you create a reproducer in ancestry OR do you have ideas around the usage so I can create the reproducer?

**Comment by kbrock** [comment]
I think this was resolved a few years ago.

Please ping me if someone still sees this.
