### ISSUE TITLE
Postgres Performance on Descendent Searches

### ISSUE THREAD

**Issue by activefx** [stefankroes/ancestry#181]
I was hoping you could give me some advice on speeding up performance on Postgres. The ancestry column is indexed, and a child search on 6 million records takes about 3.5ms. However a descendent search takes about 8.5 seconds. Do you have any suggestions for speeding up a descendent search? Any advice would be greatly appreciated.

**Comment by HarrisonB** [comment]
We just ran into this, just realizing that our index is not being used. Perhaps this could be included in the README for Postgres users?

**Comment by kbrock** [comment]
A number of options to fix this have been added to the readme.
Please let me know if any of the options do not work for you or if you have a better suggestion.
