### ISSUE TITLE
How to sort by child count

### ISSUE THREAD

**Issue by crjackso** [stefankroes/ancestry#185]
I apologize in advance if this has been asked already, but searching didn't yield anything.  I'm looking to use ancestry to help set up a leaderboard. Person A brings in others to the site and they are associated with Person A in the form of being Person A's children.  With this inheritance model in mind, I'd like to set up a leaderboard to show the top X people with the most associations(children).  In other words, is there a way to sort by child count in descending order with a limit of X?

**Comment by pnghai** [comment]
You can make a children_count column for counting cache, and tracking the counting change on those events:
- when new node added to/deleted from parent node: update parent.count with parent.descendants.count
- when node moved to another parent. update new parent and old paren's children_count

**Comment by kbrock** [comment]
Using children_count is a great solution.

Please let me know if this did not meet your needs.
Since this is quite old, and there is a solution, I am going to go ahead and close this
