### ISSUE TITLE
Preloading children

### ISSUE THREAD

**Issue by joearasin** [stefankroes/ancestry#207]
It'd be great to be able to preload children in an association - Ideally so groups of the model model can be serialized without a painful number of queries:

Ideally something like this should work

``` ruby
TreeNode.where(:whatever).includes(:children).each do |i|
  puts i.name, i.children
end
```

**Comment by ndelage** [comment]
I've tried this with a `.roots` scope like so:

`Model.roots.arrange_serializable`

But for some reason the `children` attribute of the serialized records are always empty arrays (even if _the model has children_). Any idea why?

```
> SubjectMatter.roots.arrange_serializable.first
  SubjectMatter Load (1.2ms)  SELECT "subject_matters".* FROM "subject_matters" WHERE "subject_matters"."ancestry" IS NULL  ORDER BY (case when subject_matters.ancestry is null then 0 else 1 end), subject_matters.ancestry

 => {"id"=>1, "name"=>"Example", "ancestry"=>nil, "children"=>[]}
```

**Comment by kbrock** [comment]
You want to arrange all nodes, rather than arranging just the root nodes.

```ruby
SubjectMatter.arrange
SubjectMatter.arrange_nodes(SubjectMatter.all)
```
