### ISSUE TITLE
Ruby 2.1.2, Rails 4.1.6, new error: ActiveModel::MissingAttributeError: can't write unknown attribute `parent_id'

### ISSUE THREAD

**Issue by peelman** [stefankroes/ancestry#208]
Recently updated an internal app to Ruby 2.1.2, Rails 4.1.6 and Ancestry 2.1 (was on Rails 4.0.4 and Ancestry 2.0) and now I'm seeing this error for every form that uses "parent_id" via a select box to update the parent:

    irb(main):010:0> h.parent_id=31
      Hardware Load (0.1ms)  SELECT  "hardware".* FROM "hardware"  WHERE "hardware"."id" = ? LIMIT 1  [["id", 31]]
    ActiveModel::MissingAttributeError: can't write unknown attribute `parent_id'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods/write.rb:93:in `write_attribute_with_type_cast'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods/write.rb:58:in `write_attribute'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:68:in `write_attribute'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods.rb:395:in `[]='
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/belongs_to_association.rb:70:in `replace_keys'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/belongs_to_association.rb:14:in `replace'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/singular_association.rb:17:in `writer'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/builder/association.rb:118:in `parent='
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:153:in `parent_id='
    	from (irb):10
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
    	from bin/rails:4:in `require'
    	from bin/rails:4:in `<main>'

Of course that's from the ruby console of my machine, but you get the point. I get the same error on our production server which is Ubuntu 14.04.1, same version of Ruby, obviously the same gems.

I haven't had any luck chasing it down, was hoping to find some input here as to what to try next, or if this is a legitimate bug with newer Ruby or Rails versions...

**Comment by vanderhoorn** [comment]
Ancestry's ```parent``` method was overridden in a model. Ruby allows you to do that. So it was a bug in the application, not in Ancestry.
