### ISSUE TITLE
sane_ancestry? method not working with :ancestry_column option

### ISSUE THREAD

**Issue by daniel2d2art** [stefankroes/ancestry#210]
Hi here!
**sane_ancestry?** method not working with :ancestry_column option
[https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/instance_methods.rb#L298](https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/instance_methods.rb#L298)
Thx!

**Comment by javiyu** [comment]
Thanks for opening issue @daniel2d2art, same thing happened to me, here is a pull request that will fix it https://github.com/stefankroes/ancestry/pull/227
