### ISSUE TITLE
Adding extra parameters on insert

### ISSUE THREAD

**Issue by desoleary** [stefankroes/ancestry#215]
Hi Stefan,

We are using your ancestry in development and we are finding looping through lets say 1000 records and fetching subtree_ids for each record to be very slow.  I am wondering whether you think there are any limitations in adding a lot of the instance method values directly to db on insert I am thinking about adding the following columns on insert subtree_ids, ancestor_ids, parent_id, root_id, child_ids, descendant_ids etc. obviously the column names could change in order not to cause conflicts.  More than anything wondering why you decided to puts these in instance methods rather than on the table rows themselves.

Look forward to hearing your thoughts

Thank you,

Des

**Comment by kbrock** [comment]
The goal of this pattern is to only have a single column that represents the value.

Introducing a before_save filter to populate the values may meet your needs.
I think keeping them as `parent_id` and others may work great. Just need a way to not override those methods in the has_ancestry mixin.

Please open a WIP PR with some ideas and I may be able to continue from there
