### ISSUE TITLE
Move node to another position / up down in sibling-order ?

### ISSUE THREAD

**Issue by Shmorgel** [stefankroes/ancestry#216]
Hello

It is obviously possible to select nodes by depth with :from_depth and :to_depth etc. But is it possible to insert a node at a certain position in its' node.siblings? There seems to be no method that addresses the siblings that come 'before' in order and 'after' some node. 

I would like to move a node with it's subtree one depth upwards or downwards (for instance the position after its parent), or a single node forwards and backwards in the order of its siblings.

Thank you!

**Comment by TildeWill** [comment]
@Shmorgel how'd you solve your problem? I'm looking to do the same thing
