### ISSUE TITLE
#descendants and #subtree aren't sorted

### ISSUE THREAD

**Issue by masonjm** [stefankroes/ancestry#218]
Both methods call `#scope_depth` _after_ calling `#ordered_by_ancestry`. When you call `#scope_depth` with no options, it returns the base class rather than a `Relation`. This throws away the ordering scope.

The fix seems simple (just swap the order of the method calls), but there are several tests that are checking for this ordering explicitly. Are `#descendants` and `#subtree` _suppose_ to return unordered lists?

**Comment by Fryguy** [comment]
See also issue #217 .  In addition to this problem, I don't think they sort properly anyway due to ordered_by_ancestry doing a string sort.

**Comment by kbrock** [comment]
Just resolved an issue where the query's sorting was thrown away.
Also, in postgres for our typical locale, the sorting ignores symbols (i.e.: `"/"`), so it doesn't sort the expected way.

Changing the column to be a byte oriented string (e.g. cstring), and changing the indexing may get you what you need.

I've been trying to move over to other serialization mechanisms for the path to fix this underlying flaw in the way the databases are used (postgres in particular)
