### ISSUE TITLE
Primary id column restriction? Please confirm

### ISSUE THREAD

**Issue by solars** [stefankroes/ancestry#221]
Hi,

I've got an application where the primary ID is not .id but a different field as the primary ID is something like FU_BAR_32.

This is perfectly fine and valid in rails and you can define it with self.primary_key =

However, it seems as if ancestry is restricted to the .id field, can you please confirm this?

**Comment by stefankroes** [comment]
I think I merged a patch at some point that updated ancestry to respect the configured primary key field.

**Comment by solars** [comment]
Hm, I have version 2.1.0 - is it too old then?

**Comment by solars** [comment]
There seem to be a lot of conflicting statements about custom primary keys

the primary_key_format option does not work apparently
this also dose not work

I have a model ArProperty with self.primary_key = "property_id"
The primary keys are strings like AB_DE9 etc - how can I specify this for ancestry? Cannot find out..
