### ISSUE TITLE
Decorating the results of every tree navigation

### ISSUE THREAD

**Issue by aguynamedben** [stefankroes/ancestry#222]
Hi, thanks for this amazing gem.  I'm using ancestry for a traditional internet comment thread that supports nested replies.  We allow anonymous comments, and I'm using the [https://github.com/drapergem/draper](Draper) gem to decorate anonymous comments in a certain manner.

Is there a base method is called on every tree navigation ancestry performs?  I want to systematically fudge the results of every tree navigation (root, subtree, children, etc.) without explicitly overloading each of those navigation methods.  Is there a `perform_navigation` or similar method I can overload?

I've been looking at the source code by am not familiar with the generalized terms.  Thanks for any guidance!

-Ben

**Comment by stefankroes** [comment]
No there isn't. Just have a look at the code. Also, with the decorator pattern (as implemented by `draper`) you can not override methods that are called internally by the decorated object once you've delegated.
