### ISSUE TITLE
How to include associated models?

### ISSUE THREAD

**Issue by solars** [stefankroes/ancestry#223]
Hi there, I've got a question, maybe you can help:

I've got a glass Property that has many Budget(s) with attribute 'amount'.
Property has ancestry included.

I need a performant way to get the sum of all the childrens budget.amount for a parent property.
In code it looks like:

parent = Property.create
child1 = Property.create(parent: parent, ptype: 'fu')
child2 = Property.create(parent: parent, ptype: 'fu')

child1 and child2 each have 2 budgets with for example an amount of 5
I now need to sum up the budgets of all descendants in the parent

Pseudocode would be: parent.descendants.where(ptype: 'desc').*.budgets.sum(:amount)
This obviously does not work

Can anyone tell me what is the fastest way to do this?
Thanks a lot,
Christoph

**Comment by kbrock** [comment]
Sorry - late for you, but maybe good for someone else.

I think this should work:

```ruby
parent.descendants.where(ptype: 'desc').references(:budgets).includes(:budgets).sum("budgets.amount")
```

**Comment by solars** [comment]
Thank's a lot kbrock, I'll check if I can implement it this way!
