### ISSUE TITLE
arrange with order and conditions

### ISSUE THREAD

**Issue by arpadlukacs** [stefankroes/ancestry#226]
I have a rails 3 project using ancestry 1.3.0 that has the following line:

MasterCategory.arrange(:conditions => ["type = 'MasterCategory' AND id != ?", excluded_category_id], :order => :title)

That line seems to work with the old versions.
I'm upgrading the app to rails 4 and trying to use ancestry 2.1.0 but I could not figure out how to change the above line to make it work, because it seems the latest ancestry tries to pass everything except the order item to the where, so I would need to change the string condition to a hash condition, but because of the != I can't do that.
Any idea how can I use arrange with an order and conditions together?
Thanks

**Comment by kbrock** [comment]
Looks like you are using `STI`, so you probably don't need the `where(:type => 'MasterCategory')`. So also try without including that part.

I'm not familiar with `arrange`, but I'm thinking the following should work:

```ruby
MasterCategory.where(:type => 'MasterCategory`).where.not(:id => excluded_category_id).arrange(:order => :title)
```

**Comment by kbrock** [comment]
@arpadlukacs were you able to resolve this?

**Comment by arpadlukacs** [comment]
Sorry, this issue can be closed. I can't remember what happened with me problem: I solved or ended up using a workaround. Thank you.
