### ISSUE TITLE
long descendant list and performance in mysql

### ISSUE THREAD

**Issue by saten** [stefankroes/ancestry#228]
I have a case in which I have a chain of records. 1 parent with 1 child, which has 1 child and so on. Many times. This leads to data in the ancestry column of the last child to be costantly growing in length.

I have to lookup the very last child for every root, so I need to perform a query for the last descendant for each root record. This is incredibly slow without an index on the ancestry column, but MySQL won't let me enlarge the column size more than 254 chars. If I do, the index on the column will be dropped and I will die in a fire :P

Any suggestions?

**Comment by kbrock** [comment]
I'm not sure I'd use ancestry for what sounds like an ordered list.

I am exploring using arrays, but that will have issues as well.

I think I would have all records the child of the first record. so only a max depth of 1

This PR is quite old.
Let me know how you solved this and if we can introduce anything into the codebase that will make this work better for you

--Keenan
