### ISSUE TITLE
Is there a way to limit depth?

### ISSUE THREAD

**Issue by npearson72** [stefankroes/ancestry#230]
I have a need to only allow a ancestry to go to a certain depth. I can build validations to support this but was wondering if there's anything in the api that will let me constrain the depth?

Thanks for the amazing gem

**Comment by alkx** [comment]
There's docs on this [here](https://github.com/stefankroes/ancestry#selecting-nodes-by-depth). An example:
`node.subtree(:to_depth => 2)      Subtree of node, to a depth of node.depth + 2 (self, children and grandchildren)`

**Comment by nhodges** [comment]
I think his question (at least mine is) is regarding enforcing a depth at the model level, the term "depth constraints" in the README seems to imply this, but there seems to be no such validator included.

**Comment by stefankroes** [comment]
There is nothing like this in the gem. Just add a numericallity (less_than) validation on the depth.
