### ISSUE TITLE
path omits self until persisted?

### ISSUE THREAD

**Issue by stevenjonescgm** [stefankroes/ancestry#234]
I'm not sure yet whether I'd consider it a bug in Ancestry or the wiki, but 

https://github.com/stefankroes/ancestry/wiki/Creating-a-selectbox-for-a-form-using-ancestry recommends

``` ruby
    before_save :cache_ancestry
    def cache_ancestry
      self.names_depth_cache = path.map(&:name).join('/')
    end
```

definitely doesn't work with ancestry-2.1.0/lib/ancestry/instance_methods.rb:134

The first time the model saves, `path()` will only return ancestors because self is not in the database (and has no primary_key value). I solved for myself with

``` ruby
  before_save :cache_ancestry
  def cache_ancestry
    path_names = path.map(&:name)
    path_names << self.name unless persisted?
    self.names_depth_cache = path_names.join('/')
  end
```

This would still have issues if the parents are not persisted (but that's not really supported in Ancestry anyway).

**Comment by stevenjonescgm** [comment]
Also, using ```Ancestry.path()``` in a before_save can have errors for any change in ancestry_column contents (ancestors) or change in name attribute (again because path loads new objects from DB which have a not-yet-saved value in app memory)

I'll have to think about wether after_save will help, and/or if Ancestry.path (and other tree navigation) should use ActiveRecord Association/Reflection.

It ought to be more runtime efficient/stable to use a system like inverse_of, but I'm not sure whether it is worth the effort to implement and maintain.

**Comment by stefankroes** [comment]
The wiki articles are contributed by community members and are of varying quality. I would definitely not cache this unless you run into performance issues with large numbers of nodes. What if the names change? Are you gonna expire/regenerate the caches? Just use `.path.pluck :name` when rendering the view if you are dealing with a small number of records or use something like `arrange`.

I do think it is interesting and incorrect that things like path, subtree and siblings don't include the record itself before it is persisted. That would gladly accept a patch for.

**Comment by kbrock** [comment]
There is currently a test case that explains how to solve the path name caching solution

https://github.com/stefankroes/ancestry/blob/master/test/concerns/hooks_test.rb#L16

Best of luck
Keenan
