### ISSUE TITLE
Test fails on Ruby 2.2

### ISSUE THREAD

**Issue by strzibny** [stefankroes/ancestry#237]
I am getting the following failures when trying to build RPM package for Fedora:
```
#  ruby -Ilib -Itest -rminitest/autorun -e 'Dir.glob '\''./test/**/*_test.rb'\'', &method(:require)'

Loaded Ancestry test suite environment:
  Ruby: 2.2.2
  ActiveRecord: 4.2.3
  Database: SQLite

Run options: --seed 16790

# Running:

DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:

  Rails.application.configure do
    config.active_support.test_order = :sorted
  end

Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from test_order at /usr/share/gems/gems/activesupport-4.2.3/lib/active_support/test_case.rb:42)
.................F.............................

Finished in 2.674371s, 17.5742 runs/s, 714.5606 assertions/s.

  1) Failure:
SortByAncestryTest#test_sort_by_ancestry [/builddir/build/BUILD/ancestry-2.1.0/usr/share/gems/gems/ancestry-2.1.0/test/concerns/sort_by_ancestry_test.rb:13]:
Expected: [1, 2, 4, 3, 5]
  Actual: [1, 5, 2, 4, 3]

47 runs, 1911 assertions, 1 failures, 0 errors, 0 skips
```

It works and builds fine on Fedora 21 with Ruby 2.1. I noticed that Ruby 2.2 is missing from the Travis CI matrix so it might be a Ruby 2.2 specific issue.

**Comment by strzibny** [comment]
Looking into it more I can see that the failed result is correct as well (`[1, 5, 2, 4, 3]`), just that the item with ID 5 goes before 2 (which is correctly followed by 4 and 3). In my opinion the `sort_by_ancestry` method only guarantees that children goes after their parents (which is correct), not which child goes first.

ActiveRecord nor ActiveSupport do not seem to be changing it. It looks like an issue with sorting itself (https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/class_methods.rb#L77).

**Comment by kbrock** [comment]
if you sorted by `ancestry, id` that would be consistent across tests. It would be nice to have deterministic result set, so pagination isn't funky.

**Comment by kbrock** [comment]
The tests don't even run for me on 2.2.3. It just says 'running ... success', but never actually runs the tests. So you're getting further than I am.

**Comment by kbrock** [comment]
@strzibny is this working for you now?

**Comment by kbrock** [comment]
Tests are running locally and on travis for for 2.2 and 2.3. From the command line and using wwtd
Have nailed down `Appraisal` and it seems to set things up properly

Let me know if you are having any problems @strzibny
