### ISSUE TITLE
Gem does not support primary_key_format option

### ISSUE THREAD

**Issue by shaggyone** [stefankroes/ancestry#241]
Gem declares to support :primary_key_format option but actually uses Ancestry::ANCESTRY_PATTERN constant

**Comment by nepalez** [comment]
The same problem [arising from here](https://github.com/stefankroes/ancestry/blob/2fa4381e0e21289d6800772d7f67d16efa65c4f8/lib/ancestry/has_ancestry.rb#L34)

**Comment by Spone** [comment]
Here is the recommended monkey-patch, until this option is supported: https://github.com/stefankroes/ancestry/wiki/Usage-with-UUID's

**Comment by kbrock** [comment]
is this working for you all without the patch?
Can I close this?

**Comment by halo** [comment]
> is this working for you all without the patch?

Yes, using the `primary_key_format` option works for UUIDs (tried on `4.1.0`).

> Can I close this?

I believe this issue can be closed. Thank you very much!
