### ISSUE TITLE
Needs a version Bump.

### ISSUE THREAD

**Issue by gotjosh** [stefankroes/ancestry#244]
Gemspec indicates that this version is 2.1.0 however the acceptance of a block to the arrange_serialization method was including after that version and is not syncing with the current gem, this requires that the use of this functionality must be pulled from source.

**Comment by kbrock** [comment]
Hello @gotjosh 

Just trying to verify. You are requesting the version number changes to follow Semantic Vesioning.

Bump to 2.2 because it now supports a block parameter?

Thanks

**Comment by snex** [comment]
Having the same problem. Our Gemfile has the following:

    gem "ancestry", "~> 2.1.0"

And yet the code to accept a block on arrange_serializable does not exist.

**Comment by jeremedia** [comment]
Just 'wasted' several hours before arriving at this issue report. It's very odd to have a feature's code in place, tested, and documented but not actually pushed out. What can we do to get a version bump and save future developers this discovery process?
