### ISSUE TITLE
Can't get .depth if there is same named column in table

### ISSUE THREAD

**Issue by GoodJob** [stefankroes/ancestry#255]
How can I get depth of the record if it already has .depth attribute in table, which is set to 0. How can I call this function in other way to get depth and set correct number in database? :) It is too much spaghetti adding additional column only because to know what depth is of the record :)

**Comment by kbrock** [comment]
@GoodJob `ancestry.split("/").size` ?

**Comment by kbrock** [comment]
@GoodJob were you able to solve this problem?
