### ISSUE TITLE
undefined method `ancestry_depth'

### ISSUE THREAD

**Issue by Znow** [stefankroes/ancestry#257]
Trying to use your helper, from your wiki.

But getting this error:

![image](https://cloud.githubusercontent.com/assets/265719/12531917/dd1b8c34-c206-11e5-9d5a-1c107a7aa3a2.png)

Regards

**Comment by stefankroes** [comment]
Did you enable depth caching without adding the ancestry_depth column to your table? See https://github.com/stefankroes/ancestry#options-for-has_ancestry

**Comment by Znow** [comment]
Added is, as in your docs.

```ruby
class Page < ActiveRecord::Base
    has_ancestry :depth_cache_column => :order, :cache_depth => true
    
    validates :title, presence: true
    validates :content, presence: true
    #validates :slug#, uniqueness: { scope: :type, allow_blank: true }
  end
```

Getting the same error...

**Comment by Znow** [comment]
Tried using my own column for the sake, but I ended up doing the migration in your docs.

**Comment by ImDineshSaini** [comment]
Write a migration an it it worked perfectly.

**Comment by kbrock** [comment]
add the column and this should fix your problem
