### ISSUE TITLE
Wrong childrens returned

### ISSUE THREAD

**Issue by ubermanl** [stefankroes/ancestry#258]
Hi, im having an issue with the childrens method
I have the following structure
```
Root
  Subnode1
     SubSubnode1
  Subnode2
     SubSubNode2
```
When i get Root and perform .children.first, it returns Subnode1
if i do the following it returns childrens of root again
```
root_node = Model.roots.first #correct root node
subnode_one = root_node.children.first #correct subnode1
sub_subnode_one = subnode_one.children.first 
```
what am i doing wrong?

**Comment by ubermanl** [comment]
Shame on me!, somehow i migrated ancestry column as integer... sorry to bother.

**Comment by kbrock** [comment]
@ubermanl thanks for using ancestry and following up.
