### ISSUE TITLE
Accessing node's path in before_save or after_save

### ISSUE THREAD

**Issue by tilo** [stefankroes/ancestry#267]
@stefankroes I'm running into a similar issue as #33 with ancestry 2.1.0 , Rails 4.2.4 with a Postgres DB.

```
class Node < ActiveRecord::Base
  has_ancestry(:orphan_strategy => :adopt)
  # has a name and a slug string attribute, the slug is supposed the be the path's names concatenated

  after_save :generate_slug

  # 
  def generate_slug
    puts "OBJECT: #{self.name} ; PATH IS: #{self.path.pluck(:name).inspect}"
    self.update_column(:slug , self.path.each_with_object([]) {|x,a| a << x.name}.join('/') )
  end
end
```

Objects are created in this fashion:

```
root = Node.create(:name => 'root')
child1 = root.children.create(:name => 'child1')
OBJECT: child1 ; PATH IS: ["child1"]
child1.slug
  => 'child1'    # oops!
child1.save
OBJECT: child1 ; PATH IS: ["root","child1"]
child1.slug
  => 'root/child1'
```

self.ancestors does not appear to be set/valid during the execution of the after_save hook.

Looks like this might be an issue with multiple callbacks being registered.

**Comment by kbrock** [comment]
Hello @tilo Is this resolved by #263 ?

**Comment by tilo** [comment]
will check! Is #263 released yet?

**Comment by tilo** [comment]
if so, it's also addressing issue #33

**Comment by kbrock** [comment]
T-2 years - sorry.

Pretty sure your problem was the `before_save` vs `after_save` -- that will reduce database writes as well.
