### ISSUE TITLE
Retrieve a list of objects and its root categories in one query

### ISSUE THREAD

**Issue by karianne** [stefankroes/ancestry#269]
To start with an example: I have an object model consisting of `Thing`, `Category` and `Type`.

`Category` is a tree made with ancestry. The root of each tree has a reference to `Type`, as it is assumed that all the subcategories has the same `Type`. A `Thing` has many `Category`s.

Is there any way I can retrieve a list of `Things` with their respective root `Category`s and their types without having to look it up for each `Thing`?

**Comment by kbrock** [comment]
Hello @karianne - sorry for the lag.
If you've already solved this, could you share your solution?
If not, could you help me document the problem and try for a solution?

Thanks.

```ruby
class Think
  has_many :categories
end

class Category
  has_ancestry
  belongs_to :thing # is this true?
  belongs_to :type
end

class Type
  has_many :categories
end
```

Is your request is a better version of the following?:

```ruby
things.each do |thing|
  root_category = thing.category.root
  type = root_category.type
  puts "#{thing.name} -  #{root_category.name} : of type #{type.name}"
end
```

**Comment by kbrock** [comment]
if you still have this issue, please reopen with more information
