### ISSUE TITLE
NoMethodError: undefined method `ancestry'

### ISSUE THREAD

**Issue by djass** [stefankroes/ancestry#273]
When I try to save my object in database. Of course I migrated up my database.
I done that :

```
a = Component.new
a.save
```

And I have this error : NoMethodError: undefined method `ancestry' for #Component:0x00000005c95f68

```
My model is like this :
class Component < ActiveRecord::Base
has_ancestry
end
```

My migration is like this :

```
class AddAncestryToComponent < ActiveRecord::Migration
def change
add_column :components, :acst, :integer
add_index :components, :acst
end
def down

  remove_column :components, :acst
  remove_index :components, :acst

end
end
```

Please help me, what I done wrong ?

**Comment by voke** [comment]
The column should be called `ancestry` and be of type `string` or `text`. But if you want to use a different name see the `ancestry_column` option.

**Comment by kbrock** [comment]
thanks @voke I didn't see this question

**Comment by kbrock** [comment]
Are you all set @djass ?
