### ISSUE TITLE
has_siblings? erroneously returning false

### ISSUE THREAD

**Issue by kiddrew** [stefankroes/ancestry#274]
I have a situation where a node in the tree has a sibling but `has_siblings?` is returning false.  To reproduce:

```
class Item < ActiveRecord::Base
  has_ancestry
  before_create :set_sort_order

  private

  def set_sort_order
    puts has_siblings?
  end
end

parent = Item.create(name: 'Parent')
child = Item.create(name: 'Child', parent_id: parent.id)
sibling = Item.create(name: 'Sibling', parent_id: parent.id)
```

That outputs:

```
false
false
false
```

Am I missing something?

**Comment by voke** [comment]
It's because of the `before_create` callback. `has_siblings?` checks for `siblings.count > 1` and since the sibling item isn't created yet in the `set_sort_order` method it returns **false** for all of them.

**Comment by kiddrew** [comment]
I see.  That's definitely less than intuitive, but it's probably not worth addressing since it's such a corner case.
