### ISSUE TITLE
instance variable @disable_ancestry_callbacks not initialized

### ISSUE THREAD

**Issue by zedtux** [stefankroes/ancestry#276]
I'm having those warnings when running my tests:

```
gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:272: warning: instance variable @disable_ancestry_callbacks not initialised
```

First thing, the module file `InstanceMethods` is messed from line 1 until line 119.
Second point, the instance variable `@disable_ancestry_callbacks` should be initialised somewhere.

**Comment by lzap** [comment]
I see that as well, zillion of times. Sup?

**Comment by vanderhoorn** [comment]
rake >= 11.0 I presume?

**Comment by lzap** [comment]
Yup! That is exactly it. Sorry for the noise :-)

**Comment by zedtux** [comment]
Sorry, what's the point about the rake version ? I don't get it.

**Comment by lzap** [comment]
Rake 11.0 enabled standard Ruby warnings, which ruined whole Ruby world. Noone read warnings :-)

**Comment by zedtux** [comment]
Oops... I'm the guy looking at warnings and treating them like errors :flushed:

**Comment by lzap** [comment]
> Oops... I'm the guy looking at warnings and treating them like errors :flushed:

Haha, good luck with that on a project with 30+ devs and 200+
dependencies :-)

-- 
Later,
 Lukas #lzap Zapletal

**Comment by zedtux** [comment]
It's a hard task surely, but organising some time for this task with all the developers you have should be done quite quickly :-p
