### ISSUE TITLE
Select all children for a list of parents.

### ISSUE THREAD

**Issue by teoljungberg** [stefankroes/ancestry#280]
I have a use-case where I want to receive all children for a list of parents. But, with searching the issues and the code base itself, I couldn't figure out how to do so.

I opted for a simple solution for now, but I feel like there must be a achieve the same result from using `ancestry`. Could we construct the same query we do for `children` but called on a relation instead?

**Comment by kbrock** [comment]
This is tricky. Off hand, I think I would use an `OR`. Sorry that this example uses `inject`:

```ruby
def all_children_of(parents)
  # don't modify parameters passed in
  parents = parents.dup
  # start query with children of first parent
  scope = Model.children_of(parents.pop)
  # build up the scope to include the children of other parents.
  parents.inject(scope) { |scope, parent| scope.or(Model.children_of(parent) }
end
```

You also could use `subtree_of` instead of `children_of`

**Comment by teoljungberg** [comment]
@kbrock Thanks for the quick answer. Maybe I'm missing something here, but `#or` is not defined on `AR::Relation` in Rails 4.2 - that's introduced in Rails 5.

**Comment by stefankroes** [comment]
If you really only want the children of a set of parents (not subtrees or descendants), you can use an 'in' query as all children of a certain parent have the same ancestry value. I believe a parent should have a method child_ancestry or something along those lines. You could map the parents their child ancestries and select nodes where ancestry is included in this array (Rails will generate the correct query automatically).

**Comment by kbrock** [comment]
@teoljungberg I just ran into this problem as well. I don't have the nodes in memory either. Has me wanting to move some stuff around in a drastic way. I'll keep you posted

**Comment by kbrock** [comment]
Found a better rails 5 version

```ruby
def all_children_of(parents)
  parents.inject(Model.none) { |scope, parent| scope.or(Model.children_of(parent) }
end
```

Rails 4 probably would need to use the conditions. It looks up all parents and it is kinda an internal api, but sometimes you want it to work for now:

```ruby
def all_children_of(parents)
  parents.inject(nil) { |scope, parent| s = parent.children_condition ; scope.nil? ? s : scope.or(s) } end
```

Do note, rails 5 uses ActiveRecord `or` while rails 4 uses Arel `or`

**Comment by kbrock** [comment]
I think this is similar to #308

**Comment by kbrock** [comment]
marking as a duplicate
