### ISSUE TITLE
Bulk update parent?

### ISSUE THREAD

**Issue by solars** [stefankroes/ancestry#282]
Hi,

Maybe I didn't find it but is there a way to bulk update the parent of a bunch of objects? (update_all)
Theoretically it's just a matter of mapping the ancestry string and forwarding to update_all, is that right?

Thanks,
Christoph

**Comment by stefankroes** [comment]
I think the parent has a method `child_ancestry`, you can update the ancestry of multiple records to that value using update_all.

**Comment by kbrock** [comment]
@solars were you able to resolve this?

**Comment by solars** [comment]
Not yet, still having a workaround in place

**Comment by fwoelm** [comment]
If you are using PostgreSQL, you might even be able to bulk update all descendants:

``` ruby
tree_to_move = Tree.find(100)
# ID: 100
# Ancestry Path: 1/2/3

new_parent_tree = Tree.find(1000)
# ID: 1000
# Ancestry Path: 4

# Move all of the tree node's children:
# Replace in ancestry_path (the first occurrence of):
# tree_to_move's child ancestry path (1/2/3/100)
# with
# the child ancestry path of the new parent + the ID of the tree we are moving (4/1000/100)
# so that...
# 1/2/3/100 becomes 4/1000/100
# 1/2/3/100/101 becomes 4/1000/100/101
# 1/2/3/100/102 becomes 4/1000/100/102
# ...
tree_to_move.descendants.update_all("ancestry = REGEXP_REPLACE(ancestry, '#{tree_to_move.child_ancestry}', '#{new_parent_tree.child_ancestry}/#{tree_to_move.id}')")

# Last but not least we have to move the tree node itself (we only updated descendants so far).
# Use update_column to avoid triggering the has_ancestry callback that manually updates each
# descendant record. 
tree_to_move.update_column('ancestry',  new_parent_tree.child_ancestry)
```
I have only done some preliminary testing but moving a tree with 8420 descendants (20 children with each 20 children with each 20 children) went from 16s (individual update statements) to .5s (update_all). A 32x improvement looks pretty promising :smile: It also reduces the risk of race conditions.

But: More work is needed on this.

PS: If you are not using IDs, make sure to look into string escaping for the ancestry path in the #update_all statement to make sure you are not opening yourself up to injections or unexpected behavior.

**Comment by kbrock** [comment]
I have been focused on changing the path from a ruby string concatenation  to something more sql friendly like an array. This is the case that I would like to target.

A number of people use callbacks that cache `ancestors.map(&:name)` and the like. So a pure sql update will need a ruby fallback or something.

Thanks for posting this.

**Comment by kbrock** [comment]
this was implemented.

As mentioned, currently, updating the path (where the name is in the hierarchy) is not implemented.
