### ISSUE TITLE
v2.2.1 is unusable in gems with models

### ISSUE THREAD

**Issue by ledermann** [stefankroes/ancestry#299]
I'm using ancestry in one of my gems (see [ledermann/keepr](https://github.com/ledermann/keepr)). There are models in this gem using `has_ancestry` in their class definition (e.g. [here](https://github.com/ledermann/keepr/blob/master/lib/keepr/group.rb))

After upgrading to v.2.2.1 this is not possible anymore because auf #259. I fixed it for running the tests of the gem, but using my gem in the application fails.

This is a load order issue: Accessing `connection.adapter_name` (made at class level in v2.2.1) requires a database connection to be established. But in a standard Rails application, models in gems are loaded **before** the database is connected. This results in the following error message on application startup:

    Gem Load Error is: No connection pool with id primary found.

Any ideas?

**Comment by ledermann** [comment]
Ok, fixing was a simple one, see PR #300

**Comment by kbrock** [comment]
@ledermann ancestry 2.2.2 is released. I hope that fixes your problem

**Comment by ledermann** [comment]
Thanks, it works fine now.
