### ISSUE TITLE
undefined method `scoped' when use orphan_strategy

### ISSUE THREAD

**Issue by Pogoss** [stefankroes/ancestry#301]
I'm using orphan_strategy => :restrict and using this wiki page https://github.com/stefankroes/ancestry/wiki/Using-orphan-restrict

But when i try to destroy parent i'm getting this error: undefined method `scoped'

```
    rescue Ancestry::AncestryException => exc
      @taxons = Taxon.scoped
      flash[:alert] = "Taxon #{exc.taxon.downcase}"
      render :index
    end
```

**Comment by kbrock** [comment]
Hello @pogoss 
What version of ancestry and rails (or active record) are you running?
Thanks

**Comment by Pogoss** [comment]
@kbrock 
ancestry 2.1.0
rails 4.2.6

**Comment by kbrock** [comment]
Hello @pogoss 

I wonder if the example is 3.0 code.
Would you try the rails 4.0 example and let me know if this works for you?
I will update the wiki documentation if this works for you.

```ruby
    rescue Ancestry::AncestryException => exc
      @taxons = Taxon.scoped
      flash[:alert] = "Taxon #{exc.taxon.downcase}"
      render :index
    end
```

--Keenan

**Comment by kbrock** [comment]
@Pogoss did this fix your problem?

**Comment by kbrock** [comment]
let me know if this is still a problem
