### ISSUE TITLE
`#ancestors` not playing nicely with `.last`

### ISSUE THREAD

**Issue by amilligan** [stefankroes/ancestry#302]
This:

`Wibble.ancestors.last`

now fails due to invalid SQL.  The culprit appears to be ActiveRecord's mechanism for reversing order when combined with ancestry's use of `coalesce`.  

This is with the latest Rails 4.x (4.2.7.1), ruby 2.3.1, and ancestry 2.2.1.

This is the error message:

```
     ActiveRecord::StatementInvalid:
       PG::SyntaxError: ERROR:  syntax error at or near "DESC"
       LINE 1: ... (3, 4)  ORDER BY coalesce("wibbles"."ancestry" DESC, '') ...
                                                                    ^
       : SELECT  "wibbles".* FROM "wibbles" WHERE "wibbles"."id" IN (3, 4)  ORDER BY coalesce("wibbles"."ancestry" DESC, '') DESC LIMIT 1
```

**Comment by kbrock** [comment]
@amilligan thanks

**Comment by kbrock** [comment]
@ledermann ancestry 2.2.2 is released. I hope that fixes your problem
