### ISSUE TITLE
Use this gem to show page structure for a CMS

### ISSUE THREAD

**Issue by iamdriz** [stefankroes/ancestry#309]
I'm building a CMS in rails and have a pages model that contains the following data:
~~~
id: 1
name: 'About'
slug: 'about'
parent_id: null

id: 2
name: 'Team'
slug: 'team'
parent_id: 1

id: 3
name: 'Cameron'
slug: 'cameron'
parent_id: 2
~~~

So as you can see I use the `parent_id` to specify a parent page to create a structure.

What I want to do is show this 'structure' in my view like:
~~~
About - /about
--- Team - /about/team
------ Cameron - /about/team/cameron
~~~

In my view I have:
~~~
<ul>
<% @pages.each do |page| %>
  <li>
    <%= page.parent.title rescue '' %> - /<%= page.slug %>
  </li>
<% end %>
</ul>
~~~

So currently they are all listed regardless of the `parent_id`.

How can I use the Ancestry gem to create the above structure? I'm having trouble following your documentation.

Basically in my model `page.rb` I have:
~~~
class Page < ActiveRecord::Base
  has_many :pages, class_name: "Page", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Page"
  has_ancestry :ancestry_column => :parent_id
end
~~~

And then in my controller index action I have:
~~~
@pages = Page.where(parent_id: nil).order('title asc')
@pages2 = TreeNode.subtree.arrange(:order => :title)
~~~

Where `@pages` is my original, and `@pages2` is my attempt to use this gem to structure them, but it just errors that it doesn't know what TreeNode is (the gem is installed and server restarted) so I'm assuming I'm using it incorrectly. **I'm also not sure how to display it in the view.**

Would it be possible to see an example of what I should be doing in the controller and view to display my structure in the format I have shown in my example at the top?

Any help is much appreciated. Thanks.

**Comment by kbrock** [comment]
Ancestry uses a field of the form `"/grand_parent_id/parent_id"`. The column is typically called `ancestry`.

**Comment by kbrock** [comment]
```ruby
class Page < ActiveRecord::Base
  # has_many :pages, class_name: "Page", foreign_key: "parent_id"
  # use defined children
  # belongs_to :parent, class_name: "Page"
  # use defined parent association
  has_ancestry
end
```

There is no `parent_id` column. This stores all entries in `ancestry` column
`parent_id` / `parent` and `children` are defined for you and are based upon the contents of `ancestry`
