### ISSUE TITLE
ancestry field query using LIKE instead of ILIKE

### ISSUE THREAD

**Issue by knightq** [stefankroes/ancestry#317]
Using any of the ancestry filters, the default query (on Postgresql) searches through the `ancestry` column using an ILIKE statement.

Often the primary key (id) of the tree searchable model has an integer type.
Under these circumstances, the use of ILIKE over LIKE is overwhelming and uselessly expensive.

IMHO there should be at least the possibility to set an option that forces the use of a case sensitive operator to gain in query times.

**Comment by kbrock** [comment]
@knightq the latest version uses like over ilike for rails 5. Rails 4 arel did not have the ability to do this.

**Comment by kbrock** [comment]
The solution has been in place for a few years. Please ping if you are not able to get it working
