### ISSUE TITLE
Conditional has_many accessing owner object possibly not working

### ISSUE THREAD

**Issue by danieldraper** [stefankroes/ancestry#319]
Just started using ancestry for the first time on a new project and have the following requirement "select all associated children records for the full tree". We have accounts which can have children accounts and we have members of those accounts. Reading through the [documentation](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html) under the heading Accessing the owner object the following should work, unless I have made a mistake.

`has_many :members, ->(account){ where(account_id: account.subtree_ids) }`

I've also attempted to use `Member.where` in the block. However the following does not work returning the following query AR 5:

`(0.6ms)  SELECT COUNT(*) FROM "members" WHERE "members"."account_id" = $1 AND "members"."account_id" IN ('e0f44276-740d-4405-971b-4fc6b2f3f911', '32f5e840-1a9e-4bed-87b7-dea19ecb2742', 'de75e68e-da3f-448c-a2d5-ab2dada82d96')  [["account_id", "e0f44276-740d-4405-971b-4fc6b2f3f911"]]`

This approach which I don't think is as nice does work

```
has_many :members

def members
  Member.where(account_id: subtree_ids)
end
```

Am I doing something wrong or is there an issue here? 

Possible duplicate of https://github.com/stefankroes/ancestry/issues/280

Edited: Should mention the stack is Rails 5, PostgreSQL with UUIDs

**Comment by danieldraper** [comment]
The answer was in my SQL statement above... AR applies a scope on a `has_many` which is obvious and you cannot override it like I was attempting. This is not an issue for Ancestry.

**Comment by kbrock** [comment]
Thanks for sharing @danieldraper
