### ISSUE TITLE
Rails 5 installation same as Rails 4? (documentation doesn't mention)

### ISSUE THREAD

**Issue by goelinsights** [stefankroes/ancestry#321]
Assuming it's the same as Rails 3 and 4. Per the changelog it looks like Rails 5 is supported. 

Fix is likely just adding Rails 5 to installation instructions already present for 3 and 4

**Comment by zephiro** [comment]
In rails 5.0.2 


ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column categories.parent does not exist

**Comment by kbrock** [comment]
funny. I've run on 5.0, 5.0.1, and 5.0.2.

Safe to assume you have the `ancestry` column in the `categories` table?

**Comment by votiakov** [comment]
Hello!

How do you run it with rails 5? I tried using v2.2.2 and version from master with no success. 
When I try to create children I get rollback with this error message: ActiveRecord::RecordInvalid: Validation failed: Ancestry is invalid

**Comment by kbrock** [comment]
Sounds like this has been resolved.
Please let me know if you have other issues
