### ISSUE TITLE
Rails 5: subtree method not found on Model

### ISSUE THREAD

**Issue by nodox** [stefankroes/ancestry#322]
I trying to run this snippet of code from a [railcast episode](http://railscasts.com/episodes/262-trees-with-ancestry?autoplay=true)

```
<% title "Message" %>

<%= nested_messages @message.subtree.arrange(:order => :created_at) %>

<p><%= link_to "Back to All Messages", messages_path %></p>
```

The subtree method is causing an error because I believe its not defined in rails 5. 

How do I fix this problem?

Error: `undefined method `subtree' for nil:NilClass`

**Comment by nodox** [comment]
Rails 5 requires me to whitelist the `:parent_id` attribute using strong parameters. I was able to get the project working using the railcast episode with strong parameters.

**Comment by kbrock** [comment]
@nodox thanks for the note/fix
