### ISSUE TITLE
Using Ancestry through multiple models

### ISSUE THREAD

**Issue by Naki21** [stefankroes/ancestry#323]
I am looking to try and use ancestry to deal with some nested relationships. I am a little confused as to how to go about it. My db is as follows

`Users have_many Systems => have_many Shelves => have_many Rows => have_many Tanks`

I would like to be able to access systems from tanks. Each resource has its own model and controller and everything. Is it possible to pass the ancestry functionality around to the different models? I looked as a similar questions but it didn't help. Thanks for any insight and advice!

**Comment by kbrock** [comment]
You can use `User.has_many :shelves, :through => :systems`

does seem bit much.

We used an intermediary table [relationship.rb](https://github.com/ManageIQ/manageiq/blob/master/app/models/relationship.rb) and a mixin.
It allows us to go across  models.

I've wrestled with performance implications of this approach, but it seems to be holding up.

**Comment by kbrock** [comment]
You could also use an STI approach

**Comment by kbrock** [comment]
wondering if Tank is the middle of a star vs a linear model.

Tank could have a row_id, shelf_id, and system_id.

Now the ui could let you add in the way you describe.
But I think avoiding a hierarchy all together would solve this better.

If you get a chance, please share the solution you came up with and how you liked it

closing old issues now. Open or ping me if this is still outstanding
