### ISSUE TITLE
Accessing node's path in before_save or after_save

### ISSUE THREAD

**Issue by ghost** [stefankroes/ancestry#33]
Hello,

I am using ancestry with friendly_id and attempting to write a full path of the node, with it's name seperated by slashes. I am doing this so I can do a single lookup when using Rails route globbing instead of multiple queries.

So far, path always seems to be empty. I've tried to do an AR find from irb after setting a breakpoint in the before_save method and it seems that all queries are scoped to the current records ancestry field contents.

I am not highly skilled in rails, so I might be missing something, or there might be a way to call AR without the scoping, but I am at a loss.

Hopefully you'd be able to suggest a solution. I love ancestry and it seems to fit will for this project and I'd love to move forward!

Sincere,
Nick

**Comment by tilo** [comment]
@stefankroes I'm running into the same issue with ancestry 2.1.0 , Rails 4.2.4 with a Postgres DB.

Can you please re-open this issue, or comment what might be causing this?

```
class Node < ActiveRecord::Base
  has_ancestry(:orphan_strategy => :adopt)
  # has a name and a slug string attribute, the slug is supposed the be the path's names concatenated

  after_save :generate_slug

  # 
  def generate_slug
    puts "OBJECT: #{self.name} ; PATH IS: #{self.path.pluck(:name).inspect}"
    self.update_column(:slug , self.path.each_with_object([]) {|x,a| a << x.name}.join('/') )
  end
end
```

Objects are created in this fashion:

```
root = Node.create(:name => 'root')
child1 = root.children.create(:name => 'child1')
OBJECT: child1 ; PATH IS: ["child1"]
child1.slug
  => 'child1'    # oops!
child1.save
child1.slug
  => 'root/child1'
```

**Comment by kbrock** [comment]
I really didn't like the way the ids were being updated before. Hoping the newer code will work much better for everyone
