### ISSUE TITLE
private method `warn' called for nil:NilClass

### ISSUE THREAD

**Issue by yo-gen** [stefankroes/ancestry#347]
## private method `warn' called for nil:NilClass

This error is shown on the line saying `has_ancestry` in my model.
This error does not show up in development environment but shows up on a custom environment of ours, not sure if it also shows up on production.

I discovered that the reason for this was following line in environments file.

`config.active_record.logger = nil`

Then fixed this with using [null logger gem](https://github.com/karafka/null-logger) and replacing the line with
`config.active_record.logger = NullLogger.new`

Any thoughts or does someone know the reason for this?

**Comment by kbrock** [comment]
I noticed the test environment does setup the logger, but that is for tests only.
The code does not log at all. (from what I can tell)

**Comment by kbrock** [comment]
please reopen if you are still having this problem
