### ISSUE TITLE
Orderly destroy

### ISSUE THREAD

**Issue by brendon** [stefankroes/ancestry#351]
Hi @kbrock, I was wondering what you thought of this as an idea:

In my application, sometimes children will do things to their parents when the child is being destroyed. I know these days AR has a `destroyed_by_association` method that can be checked, but now that I think of it, I'm not sure `ancestry` will be triggering this anyway since it does a bulk destroy. Anyway, with these types of callbacks things can go haywire if say a parent is deleted before its descendants. In my application I override like so:

```
    define_method :apply_orphan_strategy do
      unless new_record?
        children.all.each { |child| child.destroy }
      end
    end
```

I call this 'orderly destroy' in that it steps down the tree and starts at the leaves and deletes inward. Would you be open to adding this as an orphan strategy? I suspect it could be made more efficient if we loaded all `descendants`, arranged them, then stepped them in memory, but maybe not.

**Comment by kbrock** [comment]
@brendon This changes a single query into a parent/child N+1 queries.
Trying very hard to get away from our ruby centric logic here and moving towards using sql queries

**Comment by brendon** [comment]
Thanks @kbrock, fetching all descendants in the one query then arranging them and destroying them from the leaves inward would keep the single query concept, is that correct? Would you accept that as an option?

I'm not suggesting this be the default orphan strategy, just an option. :)

**Comment by fwoelm** [comment]
It would be a single query to *fetch* all the children, but each call to destroy triggers its own DELETE statement. Nevertheless, good to have your alternative documented here!

**Comment by kbrock** [comment]
strings are no longer indexed the way they used to in the c/single byte strings.
This causes problems with sorting in postgres.

So that probably needs to be fixed so we know the order to delete the records.
I have not deleted records in bulk.
Have been meaning to put together a performance suite to check the performance of the various methods.

**Comment by kbrock** [comment]
One more note: You may need to take advantage of `without_ancestry_callbacks` if you are doing the ancestry pruning yourself.

Closing this. Please open again if there are more questions

**Comment by brendon** [comment]
Thanks @kbrock. Yes I guess `touch_ancestors_callback` will be run otherwise for each destroy. It'd only need to be run for the parent node being deleted. Thanks for the heads up :)

**Comment by kbrock** [comment]
A few notes:

the order of destroy has been fixed to go from leaf to child.
more extensibility options have been introduced to hopefully give you what you want.

**Comment by brendon** [comment]
Thanks @kbrock! :)
