### ISSUE TITLE
Issue with changes in 3.0.1 and overridden find method on models

### ISSUE THREAD

**Issue by kilink** [stefankroes/ancestry#352]
We have a model that has a custom find method, which is now not getting called when setting parent_id on the model. I believe it's related to the scoping changes in #348. I can post additional details if needed.

**Comment by kbrock** [comment]
@kilink please share more.

Is the `parent_id` in a default scope or something?
Can you create a failing test case or shed some snippets that could help us work towards a failing test?

thanks

**Comment by kilink** [comment]
Here's a simple example.

```ruby
class Folder < ActiveRecord::Base
  has_ancestry cache_depth: true

  def self.find(id)
    puts caller
    puts 'Folder.find called'
    super(id)
  end
end
```

Executing the following:

```ruby
Folder.new(parent_id: 1234)
```
On ancestry 3.0.0, "Folder.find called" is printed. On ancestry 3.0.1, it is not. Obviously in our case the overridden find method is doing more than this, which is why it is causing issues.

If I add a 'puts caller' in the find method, this is the relevant part of the traceback I get with ancestry 3.0.0:

```
ancestry-3.0.0/lib/ancestry/instance_methods.rb:321:in `block in unscoped_find'
activerecord-4.2.9/lib/active_record/scoping/default.rb:33:in `block in unscoped'
activerecord-4.2.9/lib/active_record/relation.rb:302:in `scoping'
activerecord-4.2.9/lib/active_record/scoping/default.rb:33:in `unscoped'
ancestry-3.0.0/lib/ancestry/instance_methods.rb:321:in `unscoped_find'
ancestry-3.0.0/lib/ancestry/instance_methods.rb:156:in `parent_id='
```

**Comment by kilink** [comment]
Relevant traceback when using ancestry 3.0.1:

```
activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:444:in `find_one'
activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:71:in `find'
ancestry-3.0.1/lib/ancestry/instance_methods.rb:325:in `block in unscoped_find'
ancestry-3.0.1/lib/ancestry/instance_methods.rb:331:in `block in unscoped_where'
ancestry-3.0.1/lib/ancestry/class_methods.rb:206:in `unscoped_where'
ancestry-3.0.1/lib/ancestry/instance_methods.rb:330:in `unscoped_where'
ancestry-3.0.1/lib/ancestry/instance_methods.rb:323:in `unscoped_find'
ancestry-3.0.1/lib/ancestry/instance_methods.rb:157:in `parent_id='
```

**Comment by kilink** [comment]
Looks like it is definitely caused by this [change to unscoped_find](https://github.com/stefankroes/ancestry/commit/0bd6bcbab8cfa102051c119c09a5c4e974dc701d#diff-46e331d157085e6c560dd10be25071dcL321) in #348.

**Comment by kilink** [comment]
One thing I forgot to mention is that our model is using Single Table Inheritance.

**Comment by kilink** [comment]
Okay, so it boils down to calling `find` on a relation instead of the ancestry_base_class directly.

This is an older, legacy code base, so perhaps our expectations are wrong or overriding the find method was not the correct way to go about achieving what we were trying to do. It's definitely error prone, since anywhere in our code base that uses a relation instead of the find class method will be similarly affected.

**Comment by kbrock** [comment]
can you add the find method in a module

and then mix it into your base class and all relationships that point to that class?

This seems to be a confusing part of rails. Also custom finders are currently discouraged (with no real alternative)

Please ping if you are still looking for a solution here.
If you solved it, and think it would be helpful, please share

thnx
