### ISSUE TITLE
[Regression] ordered_by_ancestry_and broken

### ISSUE THREAD

**Issue by Mingan** [stefankroes/ancestry#353]
Hi,

I just tried to update ancestry 2.2.2 -> 3.0.1 and our test suite froze in an infinite recursion. I downgraded to 3.0.0 and the problem persists.

Digging in, the problem appear when `ordered_by_ancestry_and` is called. As it is been [redefined](https://github.com/stefankroes/ancestry/compare/v2.2.2...v3.0.0#diff-8f2e9f299de2ed3dfab16cceb84abf43R55) it is a scope calling itself which matches the observation. I assume, it's meant to call `ordered_by_ancestry` which now accepts additional custom ordering.

**Comment by kbrock** [comment]
Hello @Mingan 

Thanks for the find.
I fixed the problem but am running into issues writing the test.

Postgres does not define collation. So it has different results on different operating systems.

Looks like postgres is ignoring the symbol while sorting. So it is not sorting `1/2`, `11`, and `1/3` correctly

```sql
select * from (values('1/1'),('12/1'),('1/3')) s(a) order by a;
  a  
-----
 1/1
 12/1
 1/3
```
