### ISSUE TITLE
.arrange method filters out some records.

### ISSUE THREAD

**Issue by trafium** [stefankroes/ancestry#362]
Hi, I am implementing a forum using ancestry gem and I am having some issues with how .arrange method handles some of records. Imagine I have queried data like this:
```
[#<Foo id: 1, ancestry: nil>,
#<Foo id: 2, ancestry: "1">,
#<Foo id: 4, ancestry: "3">]
```
So i have one root node, one child of that node and one child of root which is not present in this particular query result. I expected the result of .arrange method to be something like
 ```
{
  #<Foo id: 1, ancestry: nil> => {
    #<Foo id: 2, ancestry: "1"> => {}
  },
  #<Foo id: 4, ancestry: "3"> => {}
}
```
but instead  it completely filters out Foo#4, because input data doesn't apparently contain it's parent. I understand that there could be reasons for this behaviour (like keeping same hash depth and record ancestry depth), but shouldn't the arrange method just arrange, not filter?
My use case is that I am fetching all users's comments (independent of ancestry depth) and all their children to show user answer branches  for his comments.

**Comment by kbrock** [comment]
thanks @trafium 

@trafium - what database are you using? Are the values you are showing actual, or an approximation?

@Fryguy wonder if new arrange tweaked something (especially on postgres that uses an odd order)

**Comment by trafium** [comment]
@kbrock thank you for quick response

Values are approximation indeed, but I tested it with exactly 3 records with matching ancestries.

I actually spent some time to analyse code and figured out that this is happening not exactly because of ordering in arrange method itself. All records successfully get ordered (basically by ancestry depth first) and passed to arrange_nodes method. Then in arrange method min_depth is set by first node's depth and node is assigned to resulting hash directly only if it's depth matches min_depth. 
So basically Foo with id: 4 never gets assigned as key to resulting array directly neither being assigned as some other record's child because it's parent is missing from input nodes.

The solution I used for my personal case is following:

```
def custom_arrange options = {}
  # Ancestry order removed because with my use case even when I manage to arrange 
  # all nodes, custom order will not work properly because node with depth 0 will always 
  # precede node with depth 1, also it allows ordering before invoking arrange
  arrange_nodes self.where(options)
end

def custom_arrange_nodes(nodes)
  nodes_ids = nodes.map(&:id)
  arranged = ActiveSupport::OrderedHash.new

  # assigning min_depth right from the start to work with nodes not being ordered by ancestry
  min_depth = nodes.map(&:depth).min

  index = Hash.new { |h, k| h[k] = ActiveSupport::OrderedHash.new }

  nodes.each do |node|
    children = index[node.id]
    index[node.parent_id][node] = children
    
    # Assigning node to arranged hash also when collection has no parent for this node
    if node.depth == min_depth || !nodes_ids.include?(node.parent_id)
      arranged[node] = children
    end

  end

  arranged
end
```

But as I understand my solution makes method somewhat slower (not sure how much).

**Comment by Fryguy** [comment]
Yeah, this sounds like a bug with the new arrange code.  I would expect the same thing as @trafium

**Comment by Fryguy** [comment]
@trafium Can you please make a PR with your changes?  Offhand, the changes seem good, so I'd like to play with them and if they are good I'll just merge them in.  I'm ok with a "little" slowdown for accuracy.

**Comment by trafium** [comment]
@Fryguy first time doing a PR, hope I done it right 😄

**Comment by waqarbaig07** [comment]
Guys, when will this be merged?
Thanks in advance
