### ISSUE TITLE
Is there a way to limit depth?

### ISSUE THREAD

**Issue by armchairdj** [stefankroes/ancestry#369]
I've read thru docs and source code but I can't seem to find a way to limit the maximum depth of my tree. If I want to create a 2- or 3-deep hierarchy but not allow anything to be inserted at a greater depth, is there a way to do that short of writing my own validations?

**Comment by kbrock** [comment]
Hello @armchairdj no. features like that are left to the part of code (controller?) that creates the node.

**Comment by armchairdj** [comment]
Thanks!
