### ISSUE TITLE
Is there a way to create multipleparent ?

### ISSUE THREAD

**Issue by rahmatullah5** [stefankroes/ancestry#371]
currently, i've created an organization structure but it's some of the 'children' need a multiple parent. here is my current ancestry and i've implemented it to OrgChart

![image](https://user-images.githubusercontent.com/16495060/34451193-918b25ae-ed51-11e7-9955-7694b0e6573f.png)

My target is similar like this one : 
![image](https://user-images.githubusercontent.com/16495060/34451201-bab03532-ed51-11e7-84eb-e933e7abcd13.png)

Can you give me an advice about my issue ?

**Comment by kbrock** [comment]
only works with one parent. currently only support one ancestry chain per object too

some day we would be able to have multiple ancestry columns, but no time in the near future.

good luck

**Comment by kbighorse** [comment]
Likewise, doesn't support a spouse relationship then?

**Comment by kbrock** [comment]
you can add a spouse relationship that is separate from the ancestry hierarchy.
This may meet your needs

**Comment by kbrock** [comment]
If you get a chance, please share how this worked for you.
