### ISSUE TITLE
Deprecation warning : Dangerous query method

### ISSUE THREAD

**Issue by benbonnet** [stefankroes/ancestry#378]
I guess that's the only line where coalesce can be found;
https://github.com/stefankroes/ancestry/blob/a0e2b424274f4378fa331d7b24edd08fc214e901/lib/ancestry/has_ancestry.rb#L49

Trying out with rails 5.2, getting the following :

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "coalesce(\"items\".\"ancestry\", '')". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().
```

**Comment by kbrock** [comment]
thank you @benbonnet

**Comment by yangel** [comment]
Any updates so far?

**Comment by kbrock** [comment]
https://github.com/stefankroes/ancestry/pull/384

Please let me know if this is not resolved for you

**Comment by rainerborene** [comment]
@kbrock when the next version will be released on rubygems?

**Comment by kbrock** [comment]
@rainerborene let me know if you are all set

**Comment by rainerborene** [comment]
@kbrock It works. thnks
