### ISSUE TITLE
can't working in People Model and Person form

### ISSUE THREAD

**Issue by syutran** [stefankroes/ancestry#381]
In myapp, Model is People.
del new
  @node.children.new
end

then post the form, ancestry is nil~

**Comment by kbrock** [comment]
Hello syutran

I'm not sure if you want to include `ancestry` as a hidden field in the html form on the new screen.
May want to include the `@node.id` and in the create action have something like `@node.children.create(params[:person])`

Have you gotten this working?

**Comment by kbrock** [comment]
Please let me know if fixing `def create` and the `_person.html.erb` didn't fix this
