### ISSUE TITLE
error when destroying 

### ISSUE THREAD

**Issue by cesarmarinhorj** [stefankroes/ancestry#395]
when i destroyed one register like:
Imagem.find(25).destroy!
it does:
 SELECT  "imagems".* FROM "imagems" WHERE "imagems"."id" = ? LIMIT ?  [["id", 25], ["LIMIT", 1]]
and after...
 SELECT "imagems".* FROM "imagems" WHERE ("imagems"."ancestry" LIKE 23 OR "imagems"."ancestry" = 23)

and so, destroyed two images instead the one with id: 25.
23 is the parent of image 25.
:/

My rails is 5.2.0
Thanks!

**Comment by kbrock** [comment]
Hello @cesarmarinhorj 

I think I understood your statement, could you verify?

```ruby
class Imagem
  has_ancestry
end

p = Imagem.create
c = p.children.create

Imagem.find(c.id).destroy!
Imagem.find(p.id) # does not exist
```

thanks

**Comment by kbrock** [comment]
Hello @cesarmarinhorj 

I added 3 tests to check on this.
Please re-open if you are still having this problem.

Please share the version of ancestry, rails (you said 5.2), and the database type.
Include the `has_ancestry` line, any callbacks in the destroy cycle, anything more to go on.

Thanks,
