### ISSUE TITLE
Can i use union unique?

### ISSUE THREAD

**Issue by beitaz** [stefankroes/ancestry#400]
Business need union unique index, i'm modify the migration file like this:
```ruby
add_index :categories, :ancestry
remove_index :categories, :code
add_index :categories, [:ancestry, :code], unique: true
```
Any questions?

**Comment by kbrock** [comment]
Hello @beitaz seems good to me

**Comment by kbrock** [comment]
@beitaz Could you please share with the rest of the community if this worked for you?

I'd prefer to hear back from you before closing this issue

**Comment by kbrock** [comment]
Let me know if this gave you problems. As I said, looks good to me.
