### ISSUE TITLE
Error while removing the records

### ISSUE THREAD

**Issue by yewness** [stefankroes/ancestry#401]
![screen shot 2018-08-18 at 7 59 29 pm](https://user-images.githubusercontent.com/14829481/44299062-647d9480-a321-11e8-98f1-91a8cff01f74.png)

I received this error while removing the department. After I remove the code
```

class Department
  has_ancestry
end

```

Everything went back to normal. Just want to know if this is normal or there's something that I missed out? Couldn't find information regarding to this issue elsewhere.

**Comment by kbrock** [comment]
Could you go into rails console and check `Department.primary_key`?

It looks like you have that set to `ancestry` as the primary key instead of `id`

**Comment by kbrock** [comment]
Hello @yewness 

I tried recreating your issue.

1. create a record, delete it - worked
2. create a record and a child, delete the child - worked
3. create a record and a child, delete the parent - worked

```
  def test_basic_delete
    AncestryTestDatabase.with_model do |model|
      n1 = model.create!                  #create a root node
      n1.destroy! # delete single node

      n1 = model.create!                  #create a root node
      n2 = model.create!(:parent => n1)   #create child with parent=root
      n2.destroy! # delete child

      n1 = model.create!                  #create a root node
      n2 = model.create!(:parent => n1)   #create child with parent=root
      n1.destroy! # delete parent
    end     
```

Could you please share the migration you used, and possibly a test case that reproduces the error in your repo?

Thank you

**Comment by kbrock** [comment]
I couldn't reproduce and didn't get any help from reporter.

If you can share more information, please reopen.

Thanks
