### ISSUE TITLE
Rails console and Ancestry

### ISSUE THREAD

**Issue by AlexKlim** [stefankroes/ancestry#406]
I like to use `ancestry` gem and it works well with RoR,  but when I run RoR console (rails c) 
and call any method from a model I get an error. 

ie

```ruby 
> Message.first
> NoMethodError: undefined method `has_ancestry' for Message 
```

Can I use the gem from rails console?

**Comment by kbrock** [comment]
Hello @AlexKlim 

I haven't seen this before.

I tend to have `gem "ancestry"` in my `Gemfile`
And have a `require "ancestry"` at the top of the model class (e.g.: `app/models/message.rb`)

This seems to work fine for me when I use a class (e.g.: `Message`) in the rails console.

What version of ruby, rails, and ancestry are you running?

**Comment by AlexKlim** [comment]
Hello, it looks really weird 

I've added `require "ancestry"` at the top of the model class (message) and it doesn't help. 

```bash
$ ruby -v
> ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

$ rails -v
> Rails 5.2.0

$ bundle show | grep ancestry
> * ancestry (3.0.2)
```

also, a few notes: 
- macOS 10.13.6
- zsh 5.3
- rvm 1.29.3

**Comment by kbrock** [comment]
let me know if you have more questions
