### ISSUE TITLE
Can't get Ancestry validation to pass

### ISSUE THREAD

**Issue by nikolalsvk** [stefankroes/ancestry#407]
Hi there,

I've been trying to use the gem with **STI** in my models.

I have a `WorkPackage` model (which has `ancestry` column in the DB):

```
class WorkPackage < ApplicationRecord
  has_ancestry
end
```

and I have the `Result` model which inherits `WorkPackage`:

```
class Result < WorkPackage
end
```

Everytime I try to create a Result or WorkPackage, I get 
```
ActiveRecord::RecordInvalid: Validation failed: Ancestry is invalid
```

When I try to read `ancestry` attribute from the object I'm trying to create, it's nil and it should pass the validation, but for some reason it's not.

I'm using Rails 5.1.4, Ruby 2.3.1, and PostgreSQL as DB.

**Comment by nikolalsvk** [comment]
Hey @kbrock, thanks for looking into this issue.

The thing is I have a lot more code inside WorkPackage and Result models, it might be that something is conflicting with the gem and its internals. Unfortunately, I cannot share the code nor the fields in those models.

I switched to using `closure_tree` in the meanwhile, thanks for trying to help out, I really appreciate it.

**Comment by johnmcdowall** [comment]
@nikolalsvk I know this is super late, but I just ran into this myself. I am using UUIDs as the primary key format, were you? 

I had to follow the monkey patching here https://github.com/stefankroes/ancestry/wiki/Usage-with-UUID's to get things to work. 

Just thought you might like to know for future.

**Comment by nikolalsvk** [comment]
Hey @johnmcdowall, thanks for the advice. Turns out the problem was pretty simple for me. I had a included module that was overriding `ancestry` method like this:

```
def ancestry
  []
end
```

It was a part of some legacy code in the project, and once I removed it, ancestry gem worked perfectly :)
