### ISSUE TITLE
Instance methods have something BUG when use in child class

### ISSUE THREAD

**Issue by destinyd** [stefankroes/ancestry#409]
```
class Parent < ApplicationRecord
  has_ancestry
end

class Child < Parent
end
```

```
child = Child.create
child.children.new
 => #<Parent id: nil> 
```
**it should be return #\<Child id: nil\>**

parents table has "type" column

**Comment by kbrock** [comment]
Hello @destinyd 

STI means any of the children can be returned.

`Parent.create.children` can be of type `Parent` or `Child`, but defaults to `Parent` (the parent of the STI class)
`Child.create.children` is that same association, so it has the same signature / behavior.

This is the way rails works under the covers. Not sure that we want the associations behaving differently than default rails.

Will this work for you?
```ruby
Child.create.children.new(:type => "Child")
```

I worry a little but do wonder what happens if you create the association for both classes:

```ruby
class Parent < ApplicationRecord
  has_ancestry
end

class Child < Parent
  has_ancestry
end
```

**Comment by destinyd** [comment]
All of 2 ways work for me. Thx!

BTW, the second way warning these:
```
Creating scope :roots. Overwriting existing method Subject.roots.
Creating scope :ancestors_of. Overwriting existing method Subject.ancestors_of.
Creating scope :children_of. Overwriting existing method Subject.children_of.
Creating scope :descendants_of. Overwriting existing method Subject.descendants_of.
Creating scope :subtree_of. Overwriting existing method Subject.subtree_of.
Creating scope :siblings_of. Overwriting existing method Subject.siblings_of.
Creating scope :ordered_by_ancestry. Overwriting existing method Subject.ordered_by_ancestry.
Creating scope :ordered_by_ancestry_and. Overwriting existing method Subject.ordered_by_ancestry_and.
Creating scope :path_of. Overwriting existing method Subject.path_of.
Creating scope :before_depth. Overwriting existing method Subject.before_depth.
Creating scope :to_depth. Overwriting existing method Subject.to_depth.
Creating scope :at_depth. Overwriting existing method Subject.at_depth.
Creating scope :from_depth. Overwriting existing method Subject.from_depth.
Creating scope :after_depth. Overwriting existing method Subject.after_depth.
```

**Comment by kbrock** [comment]
@destinyd Thanks for sharing the output. The first defintion is definitely the preferred way.

Sometimes you may not have the option of specifying the type, so I offered the option.

Let me know if you have any other questions.

**Comment by kbrock** [comment]
This looks like a duplicate request for #324

Wanted to record this so if it keeps coming up, we have that data and can propose a better solution
