### ISSUE TITLE
sort_by_ancestry should not require the full tree

### ISSUE THREAD

**Issue by kueda** [stefankroes/ancestry#411]
If you pass `sort_by_ancestry` an array of nodes that doesn't include the whole tree (or perhaps all the nodes on a branch), it doesn't return all the nodes you passed it. For example, this test fails:

```ruby
def test_sort_by_ancestry_with_incomplete_tree
  AncestryTestDatabase.with_model do |model|
    # - n1
    #   - n2
    #     - n3
    #   - n4
    n1 = model.create!
    n2 = model.create!(parent: n1)
    n3 = model.create!(parent: n2)
    n4 = model.create!(parent: n1)
    assert_equal [n3, n4].map(&:id), model.sort_by_ancestry([n3, n4]).map(&:id)
  end
end
```

I suspect this something to do with 8a4fb0083db246ca8e3462db148bba202b5c8b4c, in which @Fryguy replaced the existing implementation of `arrange_nodes` with one that is more efficient. @Fryguy, I have to admit I don't entirely understand how your implementation works, but do you think it could be modified so that the above test would pass?

**Comment by kbrock** [comment]
Hello @kueda 

Thank you for including a test.

I have an alternative solution, but am comparing the memory and performance implications.
If you have suggestions for the implementation, please share.

--Keenan

**Comment by Fryguy** [comment]
The sort_by_ancestry doesn't require that you have the entire tree, but it does require that you have a subtree of related nodes.  I see that the old code would essential return 2 node-sets, and this new code doesn't do that.  I'll see if I can fix this up.

**Comment by Fryguy** [comment]
@kbrock Can you label this a bug?
