### ISSUE TITLE
ActiveRecord::RecordNotFound 'id'=0

### ISSUE THREAD

**Issue by MatteoJoliveau** [stefankroes/ancestry#414]
Since version 3.0.3, when creating a child via `parent.children.find_or_create_by! name: 'Name'`, a RecordNotFound error is raised:

`ActiveRecord::RecordNotFound: Couldn't find Category with 'id'=0`

For reference, the parent has no parents.
This does not happen in 3.0.2.

**Comment by kbrock** [comment]
Hello @MatteoJoliveau 

Please help me create a test that represents your problem.
I'm not able to reproduce your issue

Thanks,
--Keenan

## my implementation

```ruby
# test/concerns/scopes_test.rb

  def test_create_parent_children
    AncestryTestDatabase.with_model(:extra_columns => {:name => :string}) do |model|
      root = model.create
      record = root.children.create
      child1 = record.parent.children.find_or_create_by! :name => 'abc'
    end
  end
```

**Comment by kbrock** [comment]
I'm sorry, I can not fix this if I can not reproduce.

I provided a test that showed it working for me.

Please reopen with a reproducer or a bugfix and I will be able to help fix your problem
