### ISSUE TITLE
sort_by_ancestry does not working correctly

### ISSUE THREAD

**Issue by AlexeyBoldak** [stefankroes/ancestry#425]
I found some issue with sort_by_ancestry method

It performs filtering for provided array

For example we have 5 nodes

n1
n2 -> n1
n3 -> n2 -> n1
n4 -> n1
n5 -> n4 -> n1
We build this array array_of_nodes =  [n1, n2, n3, n5]

sort_by_ancestry(array_of_nodes) = [n1,n2,n3]

**Comment by kbrock** [comment]
Hello,

I'm pretty sure #415 will address your issue.

It has been an issue for a long time.
without `n4` being present, it is hard to know if `n5` goes before or after `n2` (and therefore `n3`)

This used to be very slow, and it was sped up, but dropping these nodes was a side effect.
I'm hoping to get this PR merged so this issue will go away.

**Comment by kbrock** [comment]
Curiously, what version of ancestry are you using?

**Comment by kbrock** [comment]
I added a bunch of tests around this and can not reproduce your issue.

Please comment if this is still a problem
