### ISSUE TITLE
Setting #parent_id with nested attributes can result in "cannot be a descendant of itself." validation error

### ISSUE THREAD

**Issue by astyagun** [stefankroes/ancestry#429]
This is the same use case as in #423

Given:
* Tree model
* Node model
* Tree `has_many :nodes`
* Tree `accepts_nested_attributes_for :nodes`
* Node `has_ancestry`
* Nested attributes for nodes modify nodes' ancestry using `#parent_id` attributes

The problem occurs, for example, when:
* A tree has 2 nodes, one is a child of another
* And user switches nodes places by
  * Dragging child node to the top level
  * Then dragging originally parent node under the originally child node
  * Then clicking "Save" button

Then
* "cannot be a descendant of itself." validation error is generated

Possible workaround is to reset `#ancestry` of each node, that is to become a parent, to `nil`

**Comment by kbrock** [comment]
I wonder if this is #433 related as well

**Comment by kbrock** [comment]
This will need to be performed in 2 steps and not one.
