### ISSUE TITLE
Storing a description of the relationship between parent and child node

### ISSUE THREAD

**Issue by veeral-patel** [stefankroes/ancestry#443]
First of all, thanks for this gem!

So say I'm creating a ticketing system, where one ticket can have many children tickets. I'd like to store a description of the relationship between the parent ticket and a child ticket.

```
Parent1
- Child1 [blocks]
- Child2 [spawns]
```

What's the best way of implementing this? I could create a table like this:

```
parent_id | child_id | relationship
1 | 2 | blocks
1 | 3 | spawned_by
```

But then you have two sources of truth for parent-child relationships: ancestry and this table.

Ideally, I'd like to write -

```
child_ticket.relationship_to_parent
```

And get `blocks`, `spawned_by`, etc (and `nil` for root tickets).

I think adding a `relationship_to_parent` field to the `tickets` table would work. Let me know if ancestry has an out of the box way to do this, though.

**Comment by kbrock** [comment]
Just put the attribute `relationship_to_parent` in your Ticket model.
For the parent, it would be blank

May even want:
```ruby
class Ticket
  validates_presence :relationship_to_parent, :unless => :root?
end
```

**Comment by veeral-patel** [comment]
thanks @kbrock!
