### ISSUE TITLE
Storing when a model's parent was set

### ISSUE THREAD

**Issue by veeral-patel** [stefankroes/ancestry#454]
Hi -- does ancestry provide a way of storing the timestamp when a model's parent was changed?

The default migration doesn't store this timestamp, so any thoughts on how to do it myself?

```
class AddAncestryToCases < ActiveRecord::Migration[5.2]
  def change
    add_column :cases, :ancestry, :string
    add_index :cases, :ancestry
  end
end
```

**Comment by kbrock** [comment]
Hello @veeral-patel 

Rails really doesn't have granularity upon which field has been changed. It just has `updated_at`

Are you seeing `updated_at` not working, or are you asking for something different?

**Comment by veeral-patel** [comment]
> Rails really doesn't have granularity upon which field has been changed. It just has updated_at

I think you answered my question, thank you!
