### ISSUE TITLE
Indirects of each level

### ISSUE THREAD

**Issue by fercreek** [stefankroes/ancestry#468]
There is some method to get all children by level?

If I have 2 children, and they have 2 each, using the indirect method I get then 4 indirect users.

So if my indirect users have 2 more each one, can I get children from my indirect users by level?

**Comment by kbrock** [comment]
Are you able to use the `:to_depth`?  https://github.com/stefankroes/ancestry/blob/master/README.md#selecting-nodes-by-depth

**Comment by kbrock** [comment]
think the proposed solution should work for you.
please let me know if it does not and I can reopen this issue
