### ISSUE TITLE
Give parent multiple children collection

### ISSUE THREAD

**Issue by xTavi** [stefankroes/ancestry#469]
Is there a way to write something like this:

`parent.clildren = array_of_children`

Where array_of_children is an array of objects?

**Comment by kbrock** [comment]
@xTavi closest I know is `array_of_children.update_attribute(:parent => parent)`

And the more performant version `array_of_children.update_attributes(:ancestry => parent.child_ancestry)`

(`child_ancestry` is not part of public api, so may go away, but will probably be here for a while)

That may work even better if array_of_children is a scope.

**Comment by kbrock** [comment]
this could also work with `update_all`.

Though I'm not totally sure of the implications of not calling the ruby method for create.

Definitely depth caching and similar fields would not be set. So you'd need to account for those fields as well in the update_all statement. e.g.: `:depth => parent.depth+ 1` - and the sql hash would need to be converted to a sql statement.

let me know if this is still an issue.
