### ISSUE TITLE
Update parent does update ancestry, but not parent_id

### ISSUE THREAD

**Issue by viktorianer** [stefankroes/ancestry#471]
We use `ancestry` to organise tags in trees. I noticed recently, that ancestry does not update the `parent_id`, if I update the `parent` on any tag.

**Example:**
A parent tag:

```
parent = Tag.find 55
=> #<Tag::Keyword:0x007faed342e418
 id: 55,
 type: "Tag::Keyword",
 parent_id: 1,
...
```

The first child tag with this parent:

```
first_child = Tag.where(parent_id: 55).first
=> #<Tag::Keyword:0x007faeceaf03a0
 id: 57,
 type: "Tag::Keyword",
 parent_id: 55,
...
 ancestry: "1/55"
...
```

**Issue:**

I will use first tag in the tree and set it as parent of my first child.

```
first_tag = Tag.find 1
=> #<Tag::Keyword:0x007faed7044420
 id: 1,
 type: "Tag::Keyword",
 parent_id: nil,
...
```

Set it as a new parent:

```
first_child.parent = first_tag
=> #<Tag::Keyword:0x007faed7044420
 id: 1,
 type: "Tag::Keyword",
 parent_id: nil,
...

first_child.save
  Tag Load (0.9ms)  SELECT `tags`.* FROM `tags` WHERE (`tags`.`ancestry` LIKE '1/55/57/%' OR `tags`.`ancestry` = '1/55/57')
  SQL (2.1ms)  UPDATE `tags` SET `updated_at` = '2019-12-09 11:31:08', `ancestry` = '1' WHERE `tags`.`id` = 57
=> true
```

After saving and reload the child tag, the `parent_id` remains the same, but `parent` and `ancestry` are updated as expected:

```
first_child.reload
=> #<Tag::Keyword:0x007faeceaf03a0
 id: 57,
 type: "Tag::Keyword",
 parent_id: 55,
...
 ancestry: "1",
...
```

**Expected behavior:**

`first_child.parent = new_parent` should update `parent_id` to the new parent ID too.

**Rails Environment:**

 ```
 * rails (5.0.6)
	Summary: Full-stack web application framework.
	Homepage: http://rubyonrails.org
	Path: ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rails-5.0.6

  * ancestry (3.0.2)
	Summary: Organize ActiveRecord model into a tree structure
	Homepage: http://github.com/stefankroes/ancestry
	Path: ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ancestry-3.0.2
```

**Comment by kbrock** [comment]
could you peek at #472 and let me know if that describes your issue?
the tests pass for me in all versions (ruby 2.5.5, rails 4.2 - 6, pg, mysql, sqlite3)

**Comment by kbrock** [comment]
Please post if you are able to tweak #472 to make it fail in your instance.
