### ISSUE TITLE
Ability to change the `parent_id` column

### ISSUE THREAD

**Issue by dumbbaldmonkey** [stefankroes/ancestry#473]
Is there a way to change the `parent_id` column that Ancestry uses by default?
I did not see it as a potential option to pass into the `has_ancestry`.

We're using an application that has a dataset has the FK for the parent in a different column and it would be a lot easier to just set a flag instead of having to add a new duplicate column to our database.

**Comment by kbrock** [comment]
Hi @dumbbaldmonkey 

So your model has a `parent_id` and an `ancestry` column?

Think most people add the `ancestry` column, populate it from `parent_id` and then drop the `parent_id` column. - then the `parent_id` virtual column can be used (which it sounds like is your conflict)

Does your `parent_id` column point to something other than the ancestry parent?

**Comment by dumbbaldmonkey** [comment]
We have a `manager_id` which is what relates the records together in the pattern of the `parent_id` does in your examples.  I was wondering if there was a way to alias this manager_id to act like parent_id

**Comment by kbrock** [comment]
@dumbbaldmonkey the goal of ancestry is to not have the `manager_id` (or `parent_id`) in the database at all.

To use ancestry, you would add `ancestry` column, remove `manager_id` column and for your use case something like `alias manager_id parent_id`

**Comment by kbrock** [comment]
@dumbbaldmonkey You may want to try something like this:

```ruby
class Model << ActiveRecord::Base
  has_ancestry
  # not sure if you need to undefine methods parent, parent_id
  alias_attribute :parent_id, :manager_id
  belongs_to :parent, class_name: 'Model', foreign_key: :manager_id
end
```

**Comment by kbrock** [comment]
I'm unsure if you are referring to the `parent_id` used to initially populate the `ancestry` column or if you are talking about something else.

The whole point of `ancestry` is to avoid an actual `parent_id` column, which leads to N+1.
If you are happy using `parent_id` column, then maybe ancestry is not for you. You may want to look into recursive sql to leverage `parent_id` which may work better for you.

**Comment by kbrock** [comment]
@dumbbaldmonkey sorry

I misunderstood.
I added to head

think this is what you were talking about

**Comment by jdalt** [comment]
@kbrock When might we see a release with these changes in it? I could pull the `master` branch in my Gemfile, but that seems like a bad idea. Just backporting this method into 3.0.7 also doesn't seem to work.

**Comment by kbrock** [comment]
@jdalt working on gathering all the changes for `3.1` - it adds a few methods and shouldn't break too much. (only people's monkey patches)

**Comment by slim1979** [comment]
While 3.1 is not ready yet, I decided to resolve it with next trick: I add advanced field to model - parent_external_id (kind of manager_id or such other). If parent is not persited yet, I add its external_id to child and so on. Next, collection imported with activerecord-import and parent is persisted now and have an ID. Now it's possible to either go through activerecord-import result collection, or Model.pluck(:id,:external_id) and rearrange parent with this and import once again. Thus, I have 2 SQL queries instead of N+1 and other.
