### ISSUE TITLE
Ancestry for multi models (field vs. options)

### ISSUE THREAD

**Issue by mkralik** [stefankroes/ancestry#483]
I have two models: CustomField and CustomFieldOption. CustomField can be of different type (e.g. string, single-select, radiobutton, checkbox, number..). 

Now, if CustomField is of type single-select, checkbox or radiobutton it can have one or more CustomFieldOptions. 

That is already all working just fine. 

What I am trying to solve is the multi level hierarchy and support for field dependencies. Example: 
CustomField: Division, CustomFieldOptions: A, B, C

CustomFieldOption "A" can have other CustomFields as childs (from UI perspective, if a user selects option A, it will show dependent CustomFields). Right now I use polymorhic for CustomField model, but it is not that flexible, especially when I want to have deeper level of hierarchy where I need to get details from the root. 

Division (single-select field)
- A (option)
   - Team (checkbox field)
     - X (option).............
     - Y (option)
  - TeamCategory (text field)
- B (option)
- C (option)

So the hierarchy can be CustomField -> CustomFieldOption (1..n) -> CustomField (1..n) -> CustomFieldOption.....
I need to be able to see the full tree up to the root.

I was thinking to add "has_ancestry" to both CustomField and CustomFieldOption, but it stores only ID without model type, so the relations are not working for this case. I also looked into some older posts, but I think this use case is a bit different.

Any recommendations?

**Comment by jgigault** [comment]
Hello,

Having a probably bad idea but what about having one single model "CustomFieldComponent" with ancestry and implementing STI "CustomFieldInput" and "CustomFieldOption"?

Both concepts "inputs" and "options" would be stored in the same tree, each one would handle its proper logic in their own class.

Other solution would be to store your tree information in a dedicated table "CustomFieldTree" which would be in relationship with each model "inputs" and "options". You would use polymorphism.

Jean-Michel

**Comment by kbrock** [comment]
On my current project, we've implemented it in 2 different ways. (It is a large old project ...)

1. We have a polymorphic table where the various levels have different components at the various levels. It tries to pretend that it is is ancestry (just a polymorphic one), but there is quite a few indirection in there and the abstraction just became confusing.

This is pretty efficient, but slight variations in the usage look great until you count queries and realize how much work you are doing. Again: first implementation is pretty good, just stay on top of future implementations.

If you go this route, I'd suggest embracing that the form elements are not using ancestry - don't pretend that they are. (Now the node tree itself is using ancestry, and needs to embrace that)

2. We also have a form that has a bunch of different field types per level. The user gets to pick the fields / drop downs / code for populating each field ... (this problem has been solved so many times in so many languages)

This tends to introduce a lot of N+1 queries, but easy for the developers (and customer) to understand. It is also really using a relational daabase approach. Which tends to be a good thing.
If you go this route, I'd suggest reducing the number of field types that you can support. And not bending over backwards pretending that each form type is the same.

3. I lean towards the "blob" implementation. Using something like a custom "xml" that is nothing more than an html with lots of constraints. Or using something like liquid is great (depending upon your customers), that was built to help customers people build safe be safe and performant.

**Comment by kbrock** [comment]
May want to check out https://mobyinc.com/labs/building-a-dynamic-form-system

This is a fun problem that is rewritten so many times in every language.
I'm fighting the desire to designing it right now.

I'd avoid hierarchy and just create 2 classes CustomField, and CustomFieldOption:

if you want opt groups, just put that as a string in field options.
if you want inputs partitioned, just put the section_name as a string in field. rendering will group them.

Also I'd avoid custom types. Maybe a "css" type option to decide left, right, split kind of thing.

Best of luck

Please feel free to open again or ask more questions here.
I don't feel this is an issue with ancestry at this point.
