### ISSUE TITLE
Solution for multi-tenant environment?

### ISSUE THREAD

**Issue by justinperkins** [stefankroes/ancestry#484]
Not an issue per se, but looking for advice running ancestry in a multi-tenant environment, such as a `User` has many `Categories` where `Category` implements `has_ancestry`. I'd like to scope the `Category` queries to a given user.

I see a few different options but unsure what is the recommended route:

1. Create a "root" category for each user, then all user categories would be a descendent of their root category
2. Augment all predefined `ancestry` scopes with `user_id` conditions, eg `category_instance.descendants.where(user_id: 42)` (would have to be cautious with inserts, updates, & deletes)
3. Something else?

**Comment by justinperkins** [comment]
I ended up going with Option 1 and it works great, closing this out.

**Comment by kbrock** [comment]
thank you @justinperkins 
(whoa - serious lag)

I am looking into the tenancy approach here.
the initial thought is that categories can be used across all tenants.
But as you are probably too aware, that goal quickly breaks down.

I think I would have gone with option 2, but it has more unknowns/possible hidden surprises.

I do wonder if you are able to create/edit a category and hack the parent_id or ancestry value so it is for another user.

Also, thanks a lot for sharing the route you took. That will hopefully help others as many are going the multi tenant route

**Comment by justinperkins** [comment]
Ha no worries on the slow response. Got it all worked out and in a production env with Option 1 (root node owned by each tenant). Option 2 felt way too much like using default scopes, no thanks!

Great gem, love the simplicity plus our database CPU is loving the query-friendliness.
