### ISSUE TITLE
gem "activerecord", '~> 6.0' get warning "DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly"

### ISSUE THREAD

**Issue by peterklogborg** [stefankroes/ancestry#485]
Using ancestry in a rails 6 app causes the test-suite to flood the error 
"DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly"

It can be reproduced directly in the gem by changing the version of active record in the gemfile
gem "activerecord", '~> 6.0'
 and running 'rake test'

**Comment by kbrock** [comment]
please see the conversation over at https://github.com/stefankroes/ancestry/pull/442

it is due to the fact that rails has dropped support for `scope.create` and wants us to use `scope { create}` instead.

I'm looking into way of converting children from a scope to a relation. but it is non trivial

**Comment by peterklogborg** [comment]
Thank you.
Sorry that I missed the conversation.

Have a great summer

-- Best wishes
Peter Klogborg
Romerdalen 53A
5250 Odense SV
Denmark
tlf +45 22 1 33 4 55 peterklogborg@gmail.com
skype peterklogborg
discord peterklogborg#8534
