### ISSUE TITLE
Simplify ordering SQL for MySQL

### ISSUE THREAD

**Issue by brendon** [stefankroes/ancestry#486]
Hi there :) I was wondering if you'd consider simplifying the ordering SQL for MySQL instances:

https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/materialized_path.rb#L78

MySQL orders NULL FIRST by default (for ASC. NULL LAST for DESC) so we don't need to worry about an extra SQL for MySQL:
```ruby
    if %w(mysql mysql2).include?(connection.adapter_name.downcase) && ActiveRecord::VERSION::MAJOR >= 5
      reorder(arel_table[ancestry_column])
    elsif %w(sqlite sqlite3 postgresql).include?(connection.adapter_name.downcase) && ActiveRecord::VERSION::MAJOR >= 5
      reorder(
        Arel::Nodes::Ascending.new(Arel::Nodes::NamedFunction.new('COALESCE', [arel_table[ancestry_column], Arel.sql("''")])),
          order
        )
      else
        reorder(Arel.sql("(CASE WHEN #{connection.quote_table_name(table_name)}.#{connection.quote_column_name(ancestry_column)} IS NULL THEN 0 ELSE 1 END), #{connection.quote_table_name(table_name)}.#{connection.quote_column_name(ancestry_column)}"), order)
      end
```

It feels nicer not to make MySQL do extra work when it's not necessary. What do you think?

**Comment by brendon** [comment]
Sorry I see these have been moved out of scopes anyway in `master`. I am getting warnings about overwriting your scopes as I have simplified these two scopes in my model, but using your new version I'd imagine I could just overwrite those methods locally for the same effect.

Do you have a timeline on when you'll be doing a new release? :)

**Comment by kbrock** [comment]
@brendon I have a lot of documentation for the changes in ancestry. I'll see what is left to do and see about releasing soon

Do you know if the forward and reverse sorting works for mysql?
Postgres possibly has sorting with nulls in some cases, so maybe we could get both of those situations with a single call

also, the next release moves a few of the methods around, so some monkey patches may have issues.

**Comment by brendon** [comment]
MySQL sorts NULLS FIRST in ASC and NULLS LAST in DESC so a predictable pattern. I’ve heard Postgres is not so predictable and also differs per operating system. Probably best to leave the fix on there for Postgres or perhaps probe the DB for the nulls first setting and throw a warning if it will cause problems?

**Comment by brendon** [comment]
Even better Postgres allows you to specify NULLS FIRST https://www.postgresql.org/docs/8.3/queries-order.html

**Comment by kbrock** [comment]
> Even better Postgres allows you to specify NULLS FIRST https://www.postgresql.org/docs/8.3/queries-order.html
> -- @brendon 

Yea, that is what I was referencing.
By default that option is turned off. And it is a server wide setting so it tends to be not enabled.
So we'd either need to detect it or have a setting passed in.

**Comment by brendon** [comment]
Haha! Yes I remember having an older issue in GitHub around this. Yes I'm suggesting having `NULLS FIRST` in the query (only for Postgres of course). It seems to be implied by this https://www.sqlitetutorial.net/sqlite-order-by/ that NULLs are listed first in Sqlite also (the same as MySQL) though I haven't explicitly tested that, so we could use the MySQL version for that database too.

Does `ancestry` explicitly support other database types?

I found this :D https://github.com/stefankroes/ancestry/issues/131

**Comment by kbrock** [comment]
@brendon let me know if that didn't meet your needs

**Comment by brendon** [comment]
Thanks @kbrock, that looks good to me (especially for MySQL). Much appreciated.

I'm pondering proposing a PR for Rails that will switch around nulls first/last when `reverse` is used. That would make the postgres code more reliable too :)
