### ISSUE TITLE
Multiple trees in same model

### ISSUE THREAD

**Issue by sobrinho** [stefankroes/ancestry#489]
Is it possible to have multiples trees in the same model?

We do have this need in our application and I don't see how to deal with using ancestry since we have ancestry_column as a single attribute.

Any suggestions?

**Comment by kbrock** [comment]
I've started to refactor how we store/access this attribute to address a few things, among which, this is one.
But it looks like we're getting hit with some performance around this. so it will take time.

The party line is and has always been a simple "no"

But yes, I agree with you and am looking into ways that we can fix this. Just know it probably won't be within your time frame. You may want to check out the closure tree gem. That gem has different benefits/limitations, and currently multiple parents is something they provide that we can not.

Best of luck

**Comment by sobrinho** [comment]
No problem, I appreciate your effort! Thanks! s2
