### ISSUE TITLE
Configuring new primary_key_format

### ISSUE THREAD

**Issue by juliancheal** [stefankroes/ancestry#500]
Hey @kbrock,

I'm currently using ancestry version `3.0.7` and have

```
  send :remove_const, :ANCESTRY_PATTERN
  const_set :UUID_PATTERN, '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  const_set :ANCESTRY_PATTERN, %r{\A#{UUID_PATTERN}(\/#{UUID_PATTERN})*\Z}
```
to allow me to use UUIDs for keys. This breaks in `3.1.0`, but I see you have `:primary_key_format` now.

Just wanted to check that `has_ancestry cache_depth: true, primary_key_format: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' ` is now the correct way? Or do I still need to set the `ANCESTRY_PATTERN`?

**Comment by kbrock** [comment]
Mr @juliancheal 

You are correct.

- `ANCESTRY_PATTERN` has been banished - never to be heard from again.
- that format looks great without the whole `\A \Z` stuff.
- Ancestry 4.0 should keep the same syntax, but it may break again :( - eta <6 months.
- ancestry 4.0 will probably have more database formats than just `/id/id` in a string

**Comment by juliancheal** [comment]
Thanks @kbrock 💕
