### ISSUE TITLE
What is the correct return type of at_depth? Does it always return enumerable?

### ISSUE THREAD

**Issue by gerryhd** [stefankroes/ancestry#502]
Hello, we are trying to implement this gem, but we seem to be confused about the behaviour of the at_depth method.
We've been using it on ActiveRecord structures to define hierarchy. What we found is that there was a situation where at_depth returned the Model object, but we were expecting to receive an enumerable Aobject with just 1 object inside.

I tried reading the documentation but it did not help in explaining when or why at_depth would return a single object node and when it would return an enumerable (in my case a Model::ActiveRecord_Relation iterable object). Also tried reading the test suite but I only saw cases where at_depth was treated as if it returned an enumerable

**Comment by kbrock** [comment]
`at_depth` returns a scope.

Please open another issue with a little more details and we can get you fixed right up.
