### ISSUE TITLE
Restrict orphan strategy raising Ancestry::AncestryException instead of using ActiveModel::Errors

### ISSUE THREAD

**Issue by cesarjr** [stefankroes/ancestry#505]
When the `orphan_strategy` is set to `:restrict` and is tried to destroy a record with children, Ancestry is gonna raise a `Ancestry::AncestryException` with a message specifying the problem.

In a regular Active Record, if the relation is set to `dependent: : restrict_with_error` and is tried to destroy a record with dependents then AR is gonna add in `errors` collection an error `:restrict_dependent_destroy`.

It's very good because is possible to build an action at controller like this:

```
  def destroy
    if @person.destroy
      head :no_content
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  end
```

With Ancestry it is necessary to make something like this:

```
  #
  # This example is incomplete. I should check if the error message of the exception is /it has descendants/
  # The source would be bigger than this one.
  # 
  def destroy
    if @person.destroy
      head :no_content
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  rescue Ancestry::AncestryException
    error = {
      base: [
        I18n.t('activerecord.errors.models.person.attributes.base.cannot_delete_with_descendants')
      ]
    }

    render json: error, status: :unprocessable_entity
  end
```

1. In my opinion Ancestry could behave like A.R. in this specific case.
2. Would be great if I could use i18n.

What do you guys think about that?

Thanks for you great job. This gem is awesome! ❤️

**Comment by cesarjr** [comment]
Well, I solved the problem doing a validation directly at the model.

I'm gonna let the solution here because it can be useful.

I continue thinking that Ancestry could take care of this case like Active Record does with `dependent: : restrict_with_error`.

```
class MyModel < ApplicationRecord
  has_ancestry

  before_destroy :validate_children, prepend: true

  private

  def validate_children
    return unless has_children?

    errors.add(:base, :cannot_delete_having_descendants)
    throw :abort
  end
end
```

I'm gonna close this issue.

Thanks.

**Comment by kbrock** [comment]
@cesarjr I do not use this option.
Do you think it is useful for having this just an error.message?
If a user uses `save!` then they will get the error.

not sure how to introduce this change without possibly breading up code that is years old.
