### ISSUE TITLE
latest release broken?

### ISSUE THREAD

**Issue by gingerlime** [stefankroes/ancestry#513]
Thanks for ancestry! It's awesome!

Our CI returns this error when trying to build with the latest release of ancestry... hope it helps?

![Screenshot 2020-09-24 at 09 00 46](https://user-images.githubusercontent.com/524274/94111589-8de44500-fe44-11ea-8bba-5e19211ea617.png)

**Comment by HectorMF** [comment]
The 3.2.0 release was missing a couple files, if you update to 3.2.1 it should work :)

**Comment by gingerlime** [comment]
Ok, thanks for letting me know!
