### ISSUE TITLE
Suggestion:  parent should return nil instead of ActiveRecordNotFound exception.

### ISSUE THREAD

**Issue by vanboom** [stefankroes/ancestry#523]
Presently, when the `ancestry` field contains an ID, but the parent object has been deleted from the database, calling the `parent` method results in an exception. 

```ruby
user.parent = user2
user2.delete
user.parent
> ActiveRecordNotFound
```

In contrast, ActiveRecord returns nil for a `belongs_to` relation, when the foreign key has a value, but the record does not exist. 

For this example, a User "belongs_to" a Team.

```ruby
user.update_column :team_id, 123456
user.team
> nil
```
Please consider making the result of the `parent` method consistent with the handling of `belongs_to` in ActiveRecord. 

Thanks!

**Comment by kbrock** [comment]
is the thought that we will clear the value out?

**Comment by vanboom** [comment]
Good question - in our app we are trying to track down a scenario where the orphan strategy does not clear the ancestry of the children properly when a parent is destroyed so the children are left with a parent ID that no longer exists in the database.  

I think the proper handling of this case is debatable - i.e. whether to throw an exception or return nil.  I would not expect that the child record be modified when the `parent` method is called.  So simply returning `nil` if the parent does not exist would be the proposed change.
