### ISSUE TITLE
undefined local variable or method `has_ancestry'

### ISSUE THREAD

**Issue by manjunath-nm89** [stefankroes/ancestry#56]
I did the bundle install for the Ancestry Gem and did a new migration also for my table as specified , but then I get the above mentioned error.

I bundle installed the latest version of ancetry, did the migrations as well.

**Comment by joeyk16** [comment]
OMg i didnt restart mine either

**Comment by tjai89** [comment]
Me too=))

**Comment by lortza** [comment]
lol! That's exactly why I'm here too.

**Comment by sarabilmeswd2017** [comment]
me too :)

**Comment by salespitcher** [comment]
ohhhh )))
