### ISSUE TITLE
Pagination with materialized paths

### ISSUE THREAD

**Issue by jcbpl** [stefankroes/ancestry#58]
I've been exploring pagination with materialized paths. I'm adding pagination to a threaded comments system that sometimes receives thousands of comments per post. What I'm looking to do is return the page of comments in the order that would appear in the tree, top to bottom, to create a page.

Ancestry's ordered_by_ancestry scope produces an `ORDER BY` clause like this:

```
SELECT id, body, ancestry FROM comments ORDER BY (case when ancestry is null then 0 else 1 end), ancestry LIMIT 10;
```

With this query, you get all root comments first (in no particular order without another condition). I'm assuming this was the intended outcome for the purposes of the arrange method?

To get it sorted in tree order this is the first thing I tried:

```
SELECT id, body, ancestry FROM comments ORDER BY (case when ancestry is null then id else ancestry end), ancestry LIMIT 10;
```

This is better but you still end up with comments sorted by tier, so all second-level comments will come before all third-level comments, regardless of where they would appear in the actual tree. Still closer:

```
SELECT id, body, ancestry FROM comments ORDER BY (case when ancestry is null then id else CONCAT(ancestry,"/",id) end) LIMIT 10;
```

Adding a comment's own ID to the end of it's ancestry produces the expected result, but it's still not perfect, because sorting strings of integers behaves such that if you have 1, 2, 3, and 21, it would sort 1, 2, 21, 3. One solution to that is to pad the number with zeroes, but another is to translate the number to base 36 like Drupal and at least one Django add-on does.

I'm planning on implementing a system similar to Drupal/Django. Obviously making the ancestry string use base 36 instead of the actual IDs means some of the methods in ancestry would break and need to be modified to work, though that is fine for this use case.

I'm primarily wondering whether this is something that has been raised before. It seems like ancestry is primarily focused on traversing and assembling complete trees. Is that a correct assessment? I suspect that paginating huge trees is a fairly uncommon problem, but still I'm thinking about doing this work with an eye towards creating a gem, so of course I'd like to know if it's something that you think would actually be appropriate for inclusion in ancestry.

**Comment by kbrock** [comment]
There is also an issue with i18n - in some cases punctuation is ignored. so sorting 12/3/4 and 1/2/3/4 both are treated as 12345 

Nice solution.
In it's current state, I don't feel this is doable.

Are you still hoping to get a change in master?
Over the years, have you found a good trade off to simplify this problem?

**Comment by kbrock** [comment]
I updated the SO article and will add to the wiki.
I'm hoping to come up with better solutions, but at least have one for now. (only took 10 years to find a solution that was not "paginate roots, then add all their children)"
