### ISSUE TITLE
Scope like descendants, but includes self too?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stefankroes/ancestry#581]
Hi,

is there a way to get all descendant_ids, but with self included?

**Comment by kbrock** [comment]
I think `path` and `path_ids` is what you want.

May want to take a look at the image in https://github.com/stefankroes/ancestry#tree-navigation - pay special attention to the yellow highlighted nodes.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hmmm I can't remember anymore why I needed this, and subtree_ids is returning self also.. Dunno why I asked to be honest ^^ Thanks for answering though!
