### ISSUE TITLE
Should implement or document double ancestry (father+mother)

### ISSUE THREAD

**Issue by palladius** [stefankroes/ancestry#587]
Hi, your gem looks amazing! Very well documented.
However, I can't find in the README a trace of "mother/father" ancestry I need for my use case.
I would presume you implemented a SINGLE parent (tree) rather than DOUBLE parent (family tree).
If so, no problem, but I would point it out in the README.md and maybe add some pointers on how to solve that (eg, add TWO columns for a single model would work? with `mother_id` and `father_id`?)

Thanks in advance for your reply.

**Comment by kbrock** [comment]
Hello @palladius 

We currently only support a single tree using the `ancestry` column.
I do have plans to try and make that more flexible, but it is very very far off in the future.

If you have ideas how to word the documentation, please put in a PR for the README.

Thanks
