### ISSUE TITLE
Rails 7 error if remove children deleted all path 

### ISSUE THREAD

**Issue by dastanabeuov** [stefankroes/ancestry#591]
Hi

I recently updated version from 6 to 7 Rails

After the update, my descendants began to delete the entire path

Everything was working fine before the update.

What is the reason? Maybe someone already faced this problem when updating Rails

**Comment by kbrock** [comment]
I have not seen this problem

What does that mean "my descendants began to delete the entire path"

**Comment by dastanabeuov** [comment]
Thanks for the feedback. Problem solved, I just didn't upload correctly js (precompile)

**Comment by kbrock** [comment]
ok, I thought #635 may fix, but glad you are all set
