### ISSUE TITLE
gui or gem for generic tree editing?

### ISSUE THREAD

**Issue by jtoy** [stefankroes/ancestry#598]
is there a recommended gem to use if I want to have a basic web GUI to rearrange the tree?
would it be possible to build something generic for ancestry?

**Comment by kbrock** [comment]
Sorry. I do not have any suggestions.
There are quite a few issues created around bulk loading records and not loading them in the correct order.

I'll leave open for a while in case someone else can post a suggestion

**Comment by kbrock** [comment]
Not sure how well it is maintained, but I did see someone mention https://github.com/maxivak/sortable_tree_rails in our wiki

**Comment by kbrock** [comment]
If you do end up using that gem, please share your success.
