### ISSUE TITLE
Do I still need to write an arrange_as_array routine to get a children inclusive ordered list?

### ISSUE THREAD

**Issue by mices** [stefankroes/ancestry#602]
Is it still necessary to do this? Because my app errors out on this and I can't find out why
```
	def self.arrange_as_array(options={}, hash=nil)
    hash ||= arrange(options)

    arr = []
    hash.each do |node, children|
      arr << node
      arr += arrange_as_array(options, children) unless children.nil?
    end
    arr
  end
```

**Comment by kshnurov** [comment]
`arrange_as_array` is some obsolete method. Check [README on arrangment](https://github.com/stefankroes/ancestry#arrangement)

**Comment by mices** [comment]
class ItemType < ApplicationRecord
  has_ancestry
	has_many	:item_properties
	has_many	:item_types, foreign_key: :parent

  def name_for_selects
    "#{'-' * depth} #{name}"
  end

  def possible_parents
    parents = ItemType.arrange(:order => 'name')
    return new_record? ? parents : parents - subtree
  end

end

view:
    <td><%= f.collection_select :item_type_id, @item_types, :id, :name_for_selects, prompt: true, selected: @item.item_type_id %>

error:
ActionView::Template::Error (undefined method `name_for_selects' for {"id"=>1, "name"=>"General", "description"=>"", "created_at"=>Sun, 03 Nov 2019 13:58:08.000000000 UTC +00:00, "updated_at"=>Mon, 18 Nov 2019 00:00:16.000000000 UTC +00:00, "parent_id"=>nil, "lft"=>"1", "rgt"=>"2", "depth"=>0, "children_count"=>0, "ancestry"=>nil, "children"=>[]}:Hash
10:36:34 web.1  | 
10:36:34 web.1  |           value.respond_to?(:call) ? value.call(item) : item.public_send(value)
10:36:34 web.1  |                                                             ^^^^^^^^^^^^):

**Comment by kbrock** [comment]
so the error read that you are expecting a an `ItemType` object, but you have a hash.

Would you share how you set `@item_types` in your controller?

**Comment by mices** [comment]
def edit
        ItemProperty.where(item_type_id: @item.item_type_id).each do |ip|
          	@item.item_item_properties.build(item_property_id: ip.id) unless @item.item_item_properties.find_by(item_property_id: ip.id)
        end
  end

**Comment by mices** [comment]
kbrock: thanks, so i'm thinking this could be avoided by using @item_type=ItemType.find ... instead of just ItemType.find ... is that right?

**Comment by mices** [comment]
After replacing @item_types with ItemType.all in my collection_select I get a different error, Cannot find ItemProperty without an ID

**Comment by mices** [comment]
I got past that error and now the error is ActionView::Template::Error (undefined method `name_for_selects where name_for_selects is defined in ItemType model it seems to be looking for the definition in the wrong model or controller?

**Comment by mices** [comment]
OK I found that my mistake was setting items using arrange_serializable @item_types=ItemType.arrange_serializable Changing it to ItemType.all solved that error

**Comment by kbrock** [comment]
@mices has this been solved? Would you close if it has or add more comments to help us help you?

**Comment by mices** [comment]
I still don't know how to use the name_for_selects routine in item_type.rb from within the items/index.html.erb view Tried different things

**Comment by mices** [comment]
I got my code  working again by not using arrange on the model object I liked the way arrange returned a tree with just a word but I think the problem was it returned a hash and so I needed to use arrange_as_array which was my original question Calling array method on the model object caused my little name_for_selects definition in the model to be unusable and I couldn't figure out how to get it working

**Comment by mices** [comment]
I can't use the hash returned from arrange in a collection_select list, it isn't working How do I get an array from arrange instead of a hash?
