### ISSUE TITLE
release next version

### ISSUE THREAD

**Issue by kbrock** [stefankroes/ancestry#603]
- [x] https://github.com/stefankroes/ancestry/pull/607
- [x] double check if #589 introduced something bad
- [x] update the changelog
- [x] Enable test for [hooks_test.rb:35](https://github.com/stefankroes/ancestry/blob/721699e05244619cf7a585ed9f484a92dba1c297/test/concerns/hooks_test.rb#L35) -- punt. will do later

**Comment by kbrock** [comment]
probably not for this release
want to setup config for 2 things:

- [ ] materializedpath2 is the default
- [ ] no self returned from siblings
- [ ] warning message that you need to set these configs for upgrades via `gemspec.post_install_message`

**Comment by kshnurov** [comment]
Well, the main branch is already at 4.3 with a proper changelog. All you need it to update RubyGems.

#601 is just a README change, nothing to release here.

materializedpath2 is the default - I agree, but it should be a major version bump.

**Comment by kshnurov** [comment]
> It started as ascii varchar, and prefer to get it as close to the original field as possible. But I would like to document the binary case that you mention. I would like that case better if the sql generated were text and not escaped binary. Want to change mysql to a binary column. (character set=ascii would be preferable but just too hard)

I guess you should just [read](https://dev.mysql.com/doc/refman/8.0/en/charset-general.html) about database collations/character sets, what they do and when they are needed. This gem doesn't need ascii, `C`, `latin` or whatever collation there is. `binary` is all that's needed, it's faster and takes less space.

**Comment by kshnurov** [comment]
> no self returned from siblings

Why? It would be a very simple, but breaking change.
Whoever needs that, should just do `self.siblings.without(self)`, that'll produce a proper SQL.

**Comment by kshnurov** [comment]
> track down test disabled for postgres extension. Thought it was for update_descendants_after_update. I possibly already fixed this. can't find it

It's [this one](https://github.com/kshnurov/ancestry/blob/721699e05244619cf7a585ed9f484a92dba1c297/test/concerns/hooks_test.rb#L35). I'm strictly against this SQL strategy anyway, there's nothing good in skipping all Rails callbacks. It's not even updating the `updated_at` - cache won't be invalidated.
Btw, have no idea why the README says it's PG only, should also work with MySQL.

**Comment by kbrock** [comment]
re #601: In postgres, `binary` seems to use indexes better than the collation mode. So this is an improvement. But the sql generated is hard to read:

```sql
SELECT "users".* FROM "users" WHERE ("users"."ancestry" LIKE '\x383737362f25' OR "users"."ancestry" = '\x38373736')
```
