### ISSUE TITLE
Support MongoDB through Mongoid

### ISSUE THREAD

**Issue by fawzyj** [stefankroes/ancestry#62]
As mongodb is gaining popularity among web application developers and is considered the new mysql
I think supporting MongoDB will be a welcome addition to this great gem
Actually, Mongoid, the mongo ORM lib has a very similar interface to active record , so i think it will be fairly easy to make the port
Thanks

**Comment by kbrock** [comment]
The referenced gem looks like it should meet your needs (or at least at some time)
Please share if that did not meet your needs and we can see what it would take to implement mongodb here.
