### ISSUE TITLE
ancestor_ids_in_database removed?

### ISSUE THREAD

**Issue by znz** [stefankroes/ancestry#636]
ancestry (4.2.0) has `ancestor_ids_in_database`, but ancestry (4.3.0) doesn't.

[This pull request](https://github.com/stefankroes/ancestry/pull/589) removes `ancestor_ids_in_database`.

Is this intentional?

If this is intentional, what is alternative?

**Comment by kbrock** [comment]
Hello,

I introduced #637 . I will release this in `4.3.1` and is on the branch `4-3-stable`
Mostly test changes were cherry picked from other PRs to make a clean backport.
I felt more comfortable having those tests

I also added more tests focusing on the `in_database` and `after_last_save`.
I changed wording for a few internal methods from `after_save` to `after_last_save`.
I also fixed an edge case with children using `ancestry_in_database`.

Please let me know if you need anything else.

Thank you again for raising this issue.
