### ISSUE TITLE
path_ids_in_database removed?

### ISSUE THREAD

**Issue by rastamhadi** [stefankroes/ancestry#645]
ancestry 4.2.0 has `#path_ids_in_database`, but 4.3.0 doesn't.
It was removed in #589, along with `#ancestor_ids_in_database`, which was addressed in #636.
`#ancestor_ids_in_database` has since been restored in #637 and 4.3.1, but `#path_ids_in_database` is still gone.

I can't tell if `#path_ids_in_database` was meant to be part of the public interface, but I thought I'd just let you know about this potentially breaking change. There weren't any other issues asking about `#path_ids_in_database` so there may not be any demand for it to be restored.

PS: I have code that used to call `#path_ids_in_database` but I've since reworked it to call `#ancestor_ids_in_database` instead.

**Comment by kbrock** [comment]
@rastamhadi released 4.3.2
Let me know if there are any other issues.

**Comment by rastamhadi** [comment]
tqvm! We should be doing a bundle update next week. I'll let you know how it goes :)

**Comment by kbrock** [comment]
thanks so much for the followup. Let me know if you need anything else
