### ISSUE TITLE
arrange to_json

### ISSUE THREAD

**Issue by tejo** [stefankroes/ancestry#82]
Hi there,

I need to serialize an arranged tree of node to json format. If I call node.arrange.to_json I get something like:

{"#Node:0x1057dc7a0":{"#Node:0x1057ca2a8":{}}}

this is because arrange returns an hash.

actually I can get this working looping through the hash and calling to_json for every node object.

There is a better  way to do that?

Thanks

Matteo

**Comment by kbrock** [comment]
Please let me know if `arrange_serializable` does not meet your needs
