### ISSUE TITLE
Recursively destroy descendants

### ISSUE THREAD

**Issue by brendon** [stefankroes/ancestry#90]
I noticed that ancestry destroys descendants arbitrarily by calling descendants on the destroyed object. This breaks down in situations that require an orderly deconstruction of the tree and its nodes associations (starting from the bottom and working up_. I'd like to table this instead:

```
before_destroy :destroy_descendants

def destroy_descendants
  children.each { |child| child.destroy }
end
```

I thought of `children.destroy_all` but that didn't have the same effect for some reason :)

Fortunately for me, the above works with the default orphan strategy anyway, but just wanted to raise it for discussion.

**Comment by kbrock** [comment]
@brendon I just found this thread. As @miguelgraz mentions, there are quite a few issues open and it is hard to work through them all.

Are you thinking something like this?

```diff
-       unscoped_descendants.each do |descendant|
+       unscoped_descendants.order(:ancestry).reverse.each do |descendant|
          descendant.without_ancestry_callbacks do
            descendant.destroy
          end
        end
```

**Comment by brendon** [comment]
Hi @kbrock, I would think that calling `.reverse` on the returned array would be inefficient as that would be done in Ruby. You'd just call order in the opposite direction (DESC?). I assume this would probably delete the deepest descendants first but is that a valid assumption?

**Comment by kbrock** [comment]
thnx. will kick around ideas in PR

**Comment by kbrock** [comment]
thnx for help brendon

**Comment by brendon** [comment]
No worries! :D
